# =============================================================================
# validate_foundation.ps1 - static engineering review of the Foundation Layer
# -----------------------------------------------------------------------------
# Purpose:       Enforce the mission self-review checklist: no duplicate enums or
#                tables, no missing constraints/indexes, FK integrity, migration
#                order, naming consistency, documentation coverage, and schema/
#                migration sync. Designed to be run in CI after any change.
#
# Usage:         powershell -ExecutionPolicy Bypass -File scripts/validate_foundation.ps1
#
# Exit code:     0 = all checks passed; 1 = one or more failures.
# Note:          ASCII-only file (PowerShell 5.1 ANSI parsing).
# =============================================================================

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot | Split-Path -Parent
$results = New-Object System.Collections.Generic.List[object]

function Add-Result([string]$name, [bool]$ok, [string]$detail) {
    $results.Add([pscustomobject]@{ Check = $name; Status = $(if ($ok) { 'PASS' } else { 'FAIL' }); Detail = $detail })
}

function Get-Files([string]$relDir, [string]$filter = '*.sql') {
    $dir = Join-Path $root $relDir
    if (-not (Test-Path -LiteralPath $dir)) { return @() }
    return Get-ChildItem -LiteralPath $dir -Filter $filter | Sort-Object Name
}

$migrationDir = Join-Path $root 'migrations'

# --- 1. Migration inventory --------------------------------------------------
$migs = Get-Files 'migrations' '*.sql'
$migNames = @($migs | ForEach-Object { $_.Name })
$migPrefixes = @($migs | ForEach-Object {
    if ($_.Name -match '^(\d{4})_.+\.sql$') { $matches[1] } else { 'BAD' }
})
$badNames = @($migNames | Where-Object { $_ -notmatch '^\d{4}_[a-z0-9_]+\.sql$' })
Add-Result 'Migrations: naming convention NNNN_name.sql' ($badNames.Count -eq 0) ("files: " + $migNames -join ', ')

$expectedPrefixes = @('0001','0002','0003','0004','0005','0006','0007','0008','0009','0010','0011','0012','0013','0014','0015','0016','0017','0018','0019','0020','0021','0022','0023','0024','0025','0026','0027','0028','0029','0030','0031','0032','0033','0034','0035','0036','0037','0038','0039')
$prefixMatch = ($migPrefixes.Count -eq $expectedPrefixes.Count) -and
(([string]::Join(',', $migPrefixes)) -eq ([string]::Join(',', $expectedPrefixes)))
Add-Result 'Migrations: contiguous 0001-0039, no gaps/duplicates' $prefixMatch ("found: " + ($migPrefixes -join ', '))

# --- 2. Schema/migration sync (regenerate and compare) -----------------------
$snapshot = @{}
foreach ($m in $migs) { $snapshot[$m.Name] = (Get-FileHash -LiteralPath $m.FullName -Algorithm MD5).Hash }
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'scripts\build_migrations.ps1') | Out-Null
$synced = $true
$syncDetail = ''
foreach ($m in (Get-Files 'migrations' '*.sql')) {
    $h = (Get-FileHash -LiteralPath $m.FullName -Algorithm MD5).Hash
    if (-not $snapshot.ContainsKey($m.Name)) { $synced = $false; $syncDetail = "unexpected file $($m.Name)" }
    elseif ($snapshot[$m.Name] -ne $h) { $synced = $false; $syncDetail = "drift in $($m.Name)" }
}
Add-Result 'Schema/migration sync (regenerated byte-identical)' $synced $syncDetail

# --- 3. Enum uniqueness ------------------------------------------------------
$enumTypes = @()
foreach ($f in (Get-Files 'schema\01-enums')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    if ($txt -match 'CREATE\s+TYPE\s+(\w+)\s+AS\s+ENUM') { $enumTypes += $matches[1] }
}
$dupEnums = @($enumTypes | Group-Object | Where-Object { $_.Count -gt 1 } | Select-Object -ExpandProperty Name)
Add-Result 'Enums: unique, no duplicates' ($dupEnums.Count -eq 0) ("count=$($enumTypes.Count); " + ($enumTypes -join ', '))

# Enum filename must match the type it declares.
$enumNameMismatch = @()
foreach ($f in (Get-Files 'schema\01-enums')) {
    $expected = ($f.BaseName -replace '^\d+_', '')
    if ($expected -notin $enumTypes) { $enumNameMismatch += $f.Name }
}
Add-Result 'Enums: filename matches declared type' ($enumNameMismatch.Count -eq 0) ("mismatched: " + ($enumNameMismatch -join ', '))

# --- 4. Table uniqueness -----------------------------------------------------
$tables = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    if ($txt -match 'CREATE\s+TABLE\s+(\w+)') { $tables += $matches[1] }
}
$dupTables = @($tables | Group-Object | Where-Object { $_.Count -gt 1 } | Select-Object -ExpandProperty Name)
Add-Result 'Tables: unique, no duplicates' ($dupTables.Count -eq 0) ("count=$($tables.Count); " + ($tables -join ', '))

# Mission 04 relationship/junction tables: keyed by endpoint FKs + relationship
# columns, not by a natural code, so the (code | internal_code) rule does not apply.
$relationshipTables = @('product_ingredients','product_allergens','product_nutrition_values','product_health_flags','ingredient_allergens','ingredient_health_flags','ingredient_aliases','entity_relationships','product_images','product_barcodes')

# Mission 05 history tables: immutable INSERT-only snapshots. They intentionally
# carry no updated_at/deleted_at (immutable), no code/internal_code UNIQUE (several
# versions share one entity code), and are exempt from the plural-name heuristic.
# Mission 05 audit tables: operational infrastructure, not governed entities, so
# they carry no status_id and (except entity_versions) no version_number.
# Mission 07 history tables (images_history, barcodes_history) follow the same
# Mission 05 history architecture and join the same exemption list.
$historyTables = @('companies_history','brands_history','products_history','ingredients_history','allergens_history','health_flags_history','nutrition_types_history','product_categories_history','ingredient_categories_history','images_history','barcodes_history','product_images_history','product_barcodes_history')
$auditTables = @('audit_context','change_sets','audit_events','audit_log','entity_versions','version_metadata')
$infrastructureTables = $historyTables + $auditTables

# Mission 08 search tables: DERIVED READ MODELS, not governed entities. They
# deliberately carry NO status_id, NO version_number, NO audit trio, and NO
# natural code; they carry a logical {entity}_id with UNIQUE but no FK. They are
# exempt from the governed-entity heuristics and validated by their own block.
$searchTables = @('product_search_index','ingredient_search_index','brand_search_index','company_search_index')

$tableNameMismatch = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $expected = ($f.BaseName -replace '^\d+_', '')
    if ($expected -notin $tables) { $tableNameMismatch += $f.Name }
}
Add-Result 'Tables: filename matches table name' ($tableNameMismatch.Count -eq 0) ("mismatched: " + ($tableNameMismatch -join ', '))

# Plural table names (heuristic). Infrastructure/history names are conventional
# singulars/mass nouns (audit_context, audit_log, version_metadata, *_history);
# Mission 08 search tables use the singular *_search_index form (mission-named).
$nonPlural = @($tables | Where-Object { $_ -notmatch 's$' -and $_ -notin $infrastructureTables -and $_ -notin $searchTables })
Add-Result 'Tables: plural names' ($nonPlural.Count -eq 0) ("non-plural: " + ($nonPlural -join ', '))

# --- 5. Per-table structural invariants -------------------------------------
$missingPk = @(); $missingUuid = @(); $missingAudit = @(); $missingStatus = @()
$missingCodeUnique = @(); $missingComment = @()
$missingVersion = @(); $missingVersionCheck = @()
$enumCols = @{}
foreach ($t in $enumTypes) { $enumCols[$t] = $true }

foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($txt -notmatch 'PRIMARY\s+KEY') { $missingPk += $tbl }
    if ($txt -notmatch 'gen_random_uuid\(\)' -and $tbl -ne 'lifecycle_statuses') { $missingUuid += $tbl }
    # History tables are immutable INSERT-only: they intentionally have no
    # updated_at/deleted_at, so only created_at is required there. Search tables
    # are derived read models with no audit trio at all (validated separately).
    if ($tbl -notin $historyTables -and $tbl -notin $searchTables -and ($txt -notmatch 'created_at' -or $txt -notmatch 'updated_at' -or $txt -notmatch 'deleted_at')) { $missingAudit += $tbl }
    # Translation tables carry translation_status (ENUM), not status_id; audit
    # infrastructure tables carry no status_id at all; search tables carry no
    # lifecycle state (derived read models).
    if ($txt -notmatch 'status_id' -and $tbl -ne 'lifecycle_statuses' -and $tbl -notmatch '_translations$' -and $tbl -notin $auditTables -and $tbl -notin $searchTables) { $missingStatus += $tbl }
    # Lookup tables use code; canonical core entities use internal_code.
    # Mission 07 canonical entities use their natural key: barcodes.barcode,
    # images.content_hash. Translation tables are keyed by (entity_id,
    # language_id) and have neither; relationship/junction tables are keyed by
    # endpoint FKs and the relationship column set; history/audit tables are
    # keyed by version identity. Search tables are keyed by UNIQUE ({entity}_id)
    # (checked in the Mission 08 block).
    if ($txt -notmatch 'UNIQUE\s*\(\s*(code|internal_code|barcode|content_hash)\s*\)' -and $tbl -notmatch '_translations$' -and $tbl -notin $relationshipTables -and $tbl -notin $infrastructureTables -and $tbl -notin $searchTables) { $missingCodeUnique += $tbl }
    # History tables and entity_versions carry version_number; the remaining
    # audit tables are operational logs without a version counter; search tables
    # are derived read models with no governance counter.
    if (($tbl -notin $auditTables -or $tbl -eq 'entity_versions') -and $tbl -notin $searchTables -and $txt -notmatch 'version_number') { $missingVersion += $tbl }
    if (($tbl -notin $auditTables -or $tbl -eq 'entity_versions') -and $tbl -notin $searchTables -and $txt -notmatch 'CHECK\s*\(\s*version_number\s*>\s*0\s*\)') { $missingVersionCheck += $tbl }
    if (-not $txt.TrimStart().StartsWith('--')) { $missingComment += $tbl }
}
Add-Result 'Tables: id uuid PRIMARY KEY gen_random_uuid() (lifecycle_statuses = BIGINT identity exception)' ($missingPk.Count -eq 0 -and $missingUuid.Count -eq 0) ("missing: " + ($missingPk + $missingUuid) -join ', ')
Add-Result 'Tables: created_at/updated_at/deleted_at present' ($missingAudit.Count -eq 0) ("missing: " + ($missingAudit -join ', '))
Add-Result 'Tables: status_id lifecycle column present (ADR-008; translations use translation_status)' ($missingStatus.Count -eq 0) ("missing: " + ($missingStatus -join ', '))
Add-Result 'Tables: version_number governance column present' ($missingVersion.Count -eq 0) ("missing: " + ($missingVersion -join ', '))
Add-Result 'Tables: version_number CHECK (> 0) present' ($missingVersionCheck.Count -eq 0) ("missing: " + ($missingVersionCheck -join ', '))
Add-Result 'Tables: natural UNIQUE key present (code | internal_code | barcode | content_hash)' ($missingCodeUnique.Count -eq 0) ("missing: " + ($missingCodeUnique -join ', '))
Add-Result 'Tables: documentation header on every file' ($missingComment.Count -eq 0) ("missing: " + ($missingComment -join ', '))

# Translation tables must carry entity_id + language_id + translation_status and
# a uniqueness constraint over (entity_id, language_id).
$missingTransStruct = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -match '_translations$') {
        if ($txt -notmatch '\blanguage_id\b' -or
            $txt -notmatch '\btranslation_status\b' -or
            $txt -notmatch 'UNIQUE\s*\(\s*[a-z0-9_]+_id\s*,\s*language_id\s*\)') {
            $missingTransStruct += $tbl
        }
    }
}
Add-Result 'Translations: entity_id + language_id + translation_status + UNIQUE(entity, language)' ($missingTransStruct.Count -eq 0) ("missing: " + ($missingTransStruct -join ', '))

# Mission 04 relationship tables must carry the full relationship column set.
$missingRelCols = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -in $relationshipTables) {
        foreach ($c in @('source_id','confidence_level','evidence_type_id','relationship_type_id','effective_from','effective_to','verified_at','approved_at','status_id','version_number')) {
            if ($txt -notmatch ("\b" + [regex]::Escape($c) + "\b")) { $missingRelCols += "${tbl}:${c}" }
        }
    }
}
Add-Result 'Relationships: full relationship column set (source/evidence/type/timeline/status/version)' ($missingRelCols.Count -eq 0) ("missing: " + ($missingRelCols -join ', '))

# Every relationship table must carry a composite UNIQUE constraint.
$missingRelUnique = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -in $relationshipTables) {
        if ($txt -notmatch 'UNIQUE\s*\(') { $missingRelUnique += $tbl }
    }
}
Add-Result 'Relationships: composite UNIQUE present (pair+type / edge / alias)' ($missingRelUnique.Count -eq 0) ("missing: " + ($missingRelUnique -join ', '))

# entity_relationships must be the polymorphic edge table: endpoint discriminators,
# entity-type CHECK, and a no-self-loop CHECK.
$erTxt = ''
foreach ($f in (Get-Files 'schema\02-tables')) {
    if ($f.Name -match '44_entity_relationships') { $erTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'Relationships: entity_relationships polymorphic endpoints + entity-type CHECK + no-self-loop' (($erTxt -match 'subject_entity_type\s+text') -and ($erTxt -match 'object_entity_type\s+text') -and ($erTxt -match 'subject_entity_type\s+IN') -and ($erTxt -match 'no_self_loop')) 'polymorphic edge table'

# --- Mission 05 history/audit invariants -------------------------------------
# Every history table must carry the full mission version/audit column set.
$missingHistoryCols = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -in $historyTables) {
        foreach ($c in @('original_entity_id','version_number','previous_version_id','change_type','change_reason','changed_by','approved_by','source_id','confidence_level','created_at','effective_from','effective_to','superseded_at','snapshot_hash','checksum','version_status','change_set_id')) {
            if ($txt -notmatch ("\b" + [regex]::Escape($c) + "\b")) { $missingHistoryCols += "${tbl}:${c}" }
        }
    }
}
Add-Result 'History: full version/audit column set on every history table' ($missingHistoryCols.Count -eq 0) ("missing: " + ($missingHistoryCols -join ', '))

# History version identity: exactly one row per (entity, version).
$missingHistUnique = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -in $historyTables) {
        if ($txt -notmatch 'UNIQUE\s*\(\s*original_entity_id\s*,\s*version_number\s*\)') { $missingHistUnique += $tbl }
    }
}
Add-Result 'History: UNIQUE (original_entity_id, version_number) present' ($missingHistUnique.Count -eq 0) ("missing: " + ($missingHistUnique -join ', '))

# History immutability: shared guard function + a prevent_mutation trigger per
# history table (INSERT-only, no UPDATE/DELETE).
$triggerTxt = ''
foreach ($f in (Get-Files 'schema\07-triggers')) { $triggerTxt += [System.IO.File]::ReadAllText($f.FullName) + "`n" }
$funcTxt = ''
foreach ($f in (Get-Files 'schema\06-functions')) { $funcTxt += [System.IO.File]::ReadAllText($f.FullName) + "`n" }
$missingImmTrigger = @($historyTables | Where-Object { $triggerTxt -notmatch ("CREATE\s+TRIGGER\s+" + [regex]::Escape($_) + "_prevent_mutation") })
Add-Result 'History: immutability trigger wired per history table' ($missingImmTrigger.Count -eq 0) ("missing: " + ($missingImmTrigger -join ', '))
Add-Result 'History: prevent_history_mutation() guard function exists' ($funcTxt -match 'FUNCTION\s+prevent_history_mutation') 'shared INSERT-only guard'

# Mission 05 audit/version infrastructure tables all exist.
$missingAuditTable = @($auditTables | Where-Object { $_ -notin $tables })
Add-Result 'Audit: all Mission 05 audit/version tables present' ($missingAuditTable.Count -eq 0) ("missing: " + ($missingAuditTable -join ', '))

# lifecycle_statuses is the single BIGINT-identity table (ADR-008).
$lsTxt = ''
foreach ($f in (Get-Files 'schema\02-tables')) {
    if ($f.Name -match '01_lifecycle_statuses') { $lsTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'Lifecycle: lifecycle_statuses.id BIGINT GENERATED ALWAYS AS IDENTITY' ($lsTxt -match 'GENERATED\s+ALWAYS\s+AS\s+IDENTITY') 'exception to the UUID convention, ADR-008'

# is_active is demoted: status_id is authoritative, so no stored is_active column.
$storedActive = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    if ($txt -match '^\s*is_active\s+boolean') { $storedActive += ($f.BaseName -replace '^\d+_', '') }
}
Add-Result 'Tables: no stored is_active (status_id authoritative, ADR-008)' ($storedActive.Count -eq 0) ("still present: " + ($storedActive -join ', '))

# Every lookup/core-entity table that declares a status_id column must FK it to
# lifecycle_statuses(id); translation tables are governed by translation_status.
# Parsed per FOREIGN KEY statement (never across statements) so a table whose own
# status FK is lazily skipped by a cross-statement regex cannot be misattributed.
$statusFkTables = @()
foreach ($f in (Get-Files 'schema\03-constraints')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    foreach ($m in [regex]::Matches($txt, 'ALTER\s+TABLE\s+(\w+)\s+ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY\s*\(\s*(\w+)\s*\)\s*REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)')) {
        if ($m.Groups[2].Value -eq 'status_id' -and $m.Groups[3].Value -eq 'lifecycle_statuses' -and $m.Groups[4].Value -eq 'id') {
            $statusFkTables += $m.Groups[1].Value
        }
    }
}
$tablesWithStatus = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    if ($txt -match '\bstatus_id\b') { $tablesWithStatus += ($f.BaseName -replace '^\d+_', '') }
}
$expectStatusFk = @($tablesWithStatus | Where-Object { $_ -ne 'lifecycle_statuses' -and $_ -notmatch '_translations$' -and $_ -notin $searchTables })
$missingStatusFk = @($expectStatusFk | Where-Object { $_ -notin $statusFkTables })
Add-Result 'Constraints: every table with status_id FKs it -> lifecycle_statuses(id)' ($missingStatusFk.Count -eq 0) ("missing: " + ($missingStatusFk -join ', '))

# Enum type columns must reference declared enums (any table column typed as an
# enum name must exist in the enum inventory).
$unknownEnumUse = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    foreach ($e in $enumTypes) {
        if ($txt -match ("\s" + [regex]::Escape($e) + "\s") -and $txt -notmatch "CREATE\s+TYPE\s+$e") {
            # column declared with enum type name $e -> must exist in enumTypes (it does by construction here)
        }
    }
}
# Simpler direct check: the only enum-typed column today is units.dimension (unit_dimension).
foreach ($t in $enumTypes) { if ($t -notin $enumTypes) { $unknownEnumUse += $t } }
Add-Result 'Enums: every enum declared at most once and referenced correctly' ($unknownEnumUse.Count -eq 0) "see enum inventory"

# --- 5b. Mission 07 media/barcode domain invariants ----------------------------
# The canonical media and barcode tables plus their history tables must exist.
# verification_statuses is the independent verification vocabulary (ADR-008 style:
# a lookup table, not an ENUM) referenced by barcodes.verification_status_id.
$m07Tables = @('verification_statuses','images','barcodes','images_history','barcodes_history')
$missingM07 = @($m07Tables | Where-Object { $_ -notin $tables })
Add-Result 'Mission 07: all media/barcode tables present' ($missingM07.Count -eq 0) ("missing: " + ($missingM07 -join ', '))

# verification_statuses: code UNIQUE + lifecycle status FK applied in constraints.
$vsTxt = ''
foreach ($f in (Get-Files 'schema\02-tables')) {
    if ($f.Name -match '60_verification_statuses') { $vsTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'Mission 07: verification_statuses lookup (code UNIQUE, version_number, no is_active)' (($vsTxt -match 'UNIQUE\s*\(\s*code\s*\)') -and ($vsTxt -match 'version_number') -and ($vsTxt -notmatch '^\s*is_active\s+boolean')) 'lookup vocabulary, not an ENUM (ADR-008 style)'

# barcodes: natural key UNIQUE, verification_status_id, no is_active boolean.
$bcTxt = ''
foreach ($f in (Get-Files 'schema\02-tables')) {
    if ($f.Name -match '62_barcodes') { $bcTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'Mission 07: barcodes canonical entity (barcode UNIQUE, verification_status_id, no is_active)' (($bcTxt -match 'UNIQUE\s*\(\s*barcode\s*\)') -and ($bcTxt -match 'verification_status_id') -and ($bcTxt -notmatch '^\s*is_active\s+boolean')) 'status_id (lifecycle) + verification_status_id (trust) are orthogonal'

# images: content fingerprint on content_hash (Mission 05 history reserves checksum
# for row tamper-evidence), storage_uri UNIQUE, dimension/type guards present.
$imTxt = ''
foreach ($f in (Get-Files 'schema\02-tables')) {
    if ($f.Name -match '61_images') { $imTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'Mission 07: images canonical entity (storage_uri + content_hash UNIQUE, content_hash naming)' (($imTxt -match 'UNIQUE\s*\(\s*content_hash\s*\)') -and ($imTxt -match 'UNIQUE\s*\(\s*storage_uri\s*\)')) 'content_hash = content fingerprint; checksum reserved for history rows'

# --- 5c. Mission 08 search-layer invariants -----------------------------------
# Search tables are DERIVED READ MODELS: logical {entity}_id with UNIQUE but no
# FK, normalized searchable text/tokens, a ranking helper, and generated_at.
# They must NOT carry governance/lifecycle/audit columns and must NOT be FK
# targets, so the layer is completely disposable and rebuildable.
$missingSearch = @($searchTables | Where-Object { $_ -notin $tables })
Add-Result 'Search: all 4 search index tables present' ($missingSearch.Count -eq 0) ("missing: " + ($missingSearch -join ', '))

$badSearchStruct = @(); $searchFkRefs = @()
foreach ($f in (Get-Files 'schema\02-tables')) {
    $tbl = ($f.BaseName -replace '^\d+_', '')
    if ($tbl -in $searchTables) {
        $txt = [System.IO.File]::ReadAllText($f.FullName)
        $eid = ($tbl -replace '_search_index$', '_id')
        foreach ($c in @('search_name','search_text','search_tokens','language_codes','search_rank','generated_at')) {
            if ($txt -notmatch ("\b" + [regex]::Escape($c) + "\b")) { $badSearchStruct += "${tbl}:${c}" }
        }
        if ($txt -notmatch ("\b" + [regex]::Escape($eid) + "\s+uuid")) { $badSearchStruct += "${tbl}:${eid} uuid" }
        if ($txt -notmatch ("UNIQUE\s*\(\s*" + [regex]::Escape($eid) + "\s*\)")) { $badSearchStruct += "${tbl}:UNIQUE($eid)" }
        if ($txt -notmatch 'CHECK\s*\(\s*search_rank\s*>=\s*0\s*\)') { $badSearchStruct += "${tbl}:search_rank>=0" }
        # Column declarations only (prose in file headers may mention the
        # concepts; this checks the actual column layout).
        foreach ($no in @('status_id','version_number','created_at','updated_at','deleted_at','is_active')) {
            if ($txt -match ("^\s*" + [regex]::Escape($no) + "\s+(bigint|integer|numeric|text|citext|uuid|timestamptz|boolean|jsonb)")) { $badSearchStruct += "${tbl}:has ${no}" }
        }
        if ($txt -match 'REFERENCES\s+\w+') { $searchFkRefs += $tbl }
    }
}
Add-Result 'Search: derived read-model structure (entity_id UNIQUE, no FK, search fields, no governance)' ($badSearchStruct.Count -eq 0) ("issues: " + ($badSearchStruct -join ', '))
Add-Result 'Search: no inline FOREIGN KEY (REFERENCES) in search tables' ($searchFkRefs.Count -eq 0) ("with FK: " + ($searchFkRefs -join ', '))

# Search tables are not FK targets of any constraints file.
$constraintTxt = ''
foreach ($f in (Get-Files 'schema\03-constraints')) { $constraintTxt += [System.IO.File]::ReadAllText($f.FullName) + "`n" }
$searchFkTargets = @($searchTables | Where-Object { $constraintTxt -match ('REFERENCES\s+' + [regex]::Escape($_)) })
Add-Result 'Search: no foreign keys reference search tables (fully rebuildable)' ($searchFkTargets.Count -eq 0) ("referenced: " + ($searchFkTargets -join ', '))

# Search-only indexes: GIN trigram on search_name/search_text (pg_trgm, ADR-003),
# GIN on search_tokens, btree on search_rank DESC - for every search table.
$searchIndexTxt = ''
foreach ($f in (Get-Files 'schema\04-indexes')) { $searchIndexTxt += [System.IO.File]::ReadAllText($f.FullName) + "`n" }
$missingSearchIdx = @()
foreach ($tbl in $searchTables) {
    foreach ($ix in @("${tbl}_search_name_trgm_idx","${tbl}_search_text_trgm_idx","${tbl}_search_tokens_idx","${tbl}_search_rank_idx")) {
        if ($searchIndexTxt -notmatch ('CREATE\s+INDEX\s+' + [regex]::Escape($ix))) { $missingSearchIdx += $ix }
    }
    if ($searchIndexTxt -notmatch ([regex]::Escape($tbl) + '\s+USING\s+gin\s*\(\s*search_name\s+gin_trgm_ops')) { $missingSearchIdx += "${tbl}:gin(search_name gin_trgm_ops)" }
    if ($searchIndexTxt -notmatch ([regex]::Escape($tbl) + '\s+USING\s+gin\s*\(\s*search_text\s+gin_trgm_ops')) { $missingSearchIdx += "${tbl}:gin(search_text gin_trgm_ops)" }
    if ($searchIndexTxt -notmatch ('\b' + [regex]::Escape($tbl) + '\s+USING\s+gin\s*\(\s*search_tokens\s*\)')) { $missingSearchIdx += "${tbl}:gin(search_tokens)" }
    if ($searchIndexTxt -notmatch ('\b' + [regex]::Escape($tbl) + '\s*\(\s*search_rank\s+DESC\s*\)')) { $missingSearchIdx += "${tbl}:btree(search_rank DESC)" }
}
Add-Result 'Search: pg_trgm GIN + token GIN + rank indexes present' ($missingSearchIdx.Count -eq 0) ("missing: " + ($missingSearchIdx -join ', '))

# No triggers on search tables (Mission 08 rule: no synchronization triggers).
$searchTriggerTxt = ''
foreach ($f in (Get-Files 'schema\07-triggers')) { $searchTriggerTxt += [System.IO.File]::ReadAllText($f.FullName) + "`n" }
$searchTriggered = @($searchTables | Where-Object { $searchTriggerTxt -match ('ON\s+' + [regex]::Escape($_)) })
Add-Result 'Search: no triggers on search tables (no synchronization)' ($searchTriggered.Count -eq 0) ("triggered: " + ($searchTriggered -join ', '))

# --- 5d. Mission 09 certification invariants ----------------------------------
# Every table must belong to exactly one approved architectural category
# (lookup / canonical / translation / relationship / history / audit / search).
$catLookup = @('lifecycle_statuses','languages','countries','units','package_types','barcode_types','image_types','relationship_types','source_types','source_priorities','data_sources','health_flag_types','regions','ingredient_categories','product_categories','allergen_types','nutrition_types','regulatory_authorities','evidence_types','role_types','permission_types','audit_event_types','verification_statuses','measurement_bases')
$catCanonical = @('companies','brands','products','ingredients','allergens','health_flags','images','barcodes')
$catTranslation = @('company_translations','brand_translations','product_translations','ingredient_translations','allergen_translations','health_flag_translations','nutrition_type_translations','product_category_translations')
$categoryMap = @{}
foreach ($t in $catLookup) { $categoryMap[$t] = 'lookup' }
foreach ($t in $catCanonical) { $categoryMap[$t] = 'canonical' }
foreach ($t in $catTranslation) { $categoryMap[$t] = 'translation' }
foreach ($t in $relationshipTables) { $categoryMap[$t] = 'relationship' }
foreach ($t in $historyTables) { $categoryMap[$t] = 'history' }
foreach ($t in $auditTables) { $categoryMap[$t] = 'audit' }
foreach ($t in $searchTables) { $categoryMap[$t] = 'search' }
$uncategorized = @($tables | Where-Object { -not $categoryMap.ContainsKey($_) })
Add-Result 'Certification: every table classified in exactly one category' ($uncategorized.Count -eq 0) ("uncategorized: " + ($uncategorized -join ', '))

# Derived tables must resolve to existing base entities (translation/history/
# search base-entity graph). Translation and search names are mission-literal
# singulars; map them explicitly to their plural canonical base.
$derivedBase = @{}
$translationBase = @{
    'company_translations' = 'companies'; 'brand_translations' = 'brands';
    'product_translations' = 'products'; 'ingredient_translations' = 'ingredients';
    'allergen_translations' = 'allergens'; 'health_flag_translations' = 'health_flags';
    'nutrition_type_translations' = 'nutrition_types'; 'product_category_translations' = 'product_categories'
}
$searchBase = @{
    'product_search_index' = 'products'; 'ingredient_search_index' = 'ingredients';
    'brand_search_index' = 'brands'; 'company_search_index' = 'companies'
}
foreach ($kv in $translationBase.GetEnumerator()) { $derivedBase[$kv.Key] = $kv.Value }
foreach ($h in $historyTables) { $derivedBase[$h] = ($h -replace '_history$', '') }
foreach ($kv in $searchBase.GetEnumerator()) { $derivedBase[$kv.Key] = $kv.Value }
$badDerivedBase = @()
foreach ($kv in $derivedBase.GetEnumerator()) {
    if ($kv.Key -notin $tables) { $badDerivedBase += "${kv.Key}:missing-table" }
    elseif ($kv.Value -notin $tables) { $badDerivedBase += "${kv.Key}->${kv.Value}:missing-base" }
}
Add-Result 'Certification: translation/history/search base entities exist' ($badDerivedBase.Count -eq 0) ("unresolved: " + ($badDerivedBase -join ', '))

# Every canonical entity owns an immutable history table.
$missingCanonicalHistory = @($catCanonical | Where-Object { ($_ + '_history') -notin $tables })
Add-Result 'Certification: every canonical entity has immutable history' ($missingCanonicalHistory.Count -eq 0) ("missing: " + ($missingCanonicalHistory -join ', '))

# --- 5e. ECR-001 certification-blocker invariants -----------------------------
# Blocker 1/4: the product-media relationship tables, their immutable history
# tables, and the measurement-basis lookup vocabulary all exist.
$ecrTables = @('measurement_bases','product_images','product_barcodes','product_images_history','product_barcodes_history')
$missingEcr = @($ecrTables | Where-Object { $_ -notin $tables })
Add-Result 'ECR-001: all Blocker 1/4 tables present' ($missingEcr.Count -eq 0) ("missing: " + ($missingEcr -join ', '))

# Blocker 3: every history-owning table must be wired to automatic capture via
# the shared snapshot function. A table whose history is never populated is a
# certification blocker, so absence of the capture trigger is a FAIL.
$captureTracked = @($historyTables | ForEach-Object { $_ -replace '_history$', '' })
$missingCapture = @($captureTracked | Where-Object { $triggerTxt -notmatch ('CREATE\s+TRIGGER\s+' + [regex]::Escape($_) + '_capture_history') })
Add-Result 'ECR-001: automatic history-capture trigger wired per history-owning table' ($missingCapture.Count -eq 0) ("missing: " + ($missingCapture -join ', '))
Add-Result 'ECR-001: capture_entity_history() function exists' ($funcTxt -match 'FUNCTION\s+capture_entity_history') 'shared INSERT/UPDATE snapshot trigger function'

# Blocker 2: entity_relationships polymorphic endpoints validated at the storage
# layer (the edge table has no FK on subject_id/object_id by design).
Add-Result 'ECR-001: validate_entity_relationship_endpoints() function exists' ($funcTxt -match 'FUNCTION\s+validate_entity_relationship_endpoints') 'polymorphic endpoint guard'
Add-Result 'ECR-001: entity_relationships validation trigger wired' ($triggerTxt -match 'entity_relationships_validate_endpoints') 'BEFORE INSERT OR UPDATE endpoint existence check'

# ECR tables that carry the audit trio must stamp updated_at like every other
# audit-trio table (the shared set_updated_at() function, wired in 0037).
$ecrAuditTables = @('measurement_bases','product_images','product_barcodes')
$missingEcrUpdatedAt = @($ecrAuditTables | Where-Object { $triggerTxt -notmatch ('CREATE\s+TRIGGER\s+' + [regex]::Escape($_) + '_set_updated_at') })
Add-Result 'ECR-001: set_updated_at trigger wired for new audit-trio tables' ($missingEcrUpdatedAt.Count -eq 0) ("missing: " + ($missingEcrUpdatedAt -join ', '))

# Blocker 4 additive extension: the nutrition natural key gains the basis
# dimension while preserving the constraint name and the original columns
# (no column removal, no redesign - pure additive change).
$mbTxt = ''
foreach ($f in (Get-Files 'schema\03-constraints')) {
    if ($f.Name -match '09_measurement_basis') { $mbTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
$mbOk = ($mbTxt -match 'ADD\s+COLUMN\s+measurement_basis_id\s+uuid\s+NULL') -and
        ($mbTxt -match 'DROP\s+CONSTRAINT\s+product_nutrition_values_fact_unique') -and
        ($mbTxt -match 'UNIQUE\s*\(\s*product_id\s*,\s*nutrition_type_id\s*,\s*relationship_type_id\s*,\s*measurement_basis_id\s*\)') -and
        ($mbTxt -match 'REFERENCES\s+measurement_bases\s*\(\s*id\s*\)')
Add-Result 'ECR-001: measurement_basis_id additive (nullable column + FK + extended natural key, name preserved)' $mbOk 'Blocker 4 natural-key extension'

# ECR migration files exist (0032-0037); their byte-identity with schema/ is
# enforced by the sync check above.
$ecrMigs = @('0032_ecr_product_media_tables.sql','0033_ecr_product_media_history_tables.sql','0034_ecr_constraints.sql','0035_ecr_indexes.sql','0036_ecr_functions.sql','0037_ecr_triggers.sql')
$missingEcrMig = @($ecrMigs | Where-Object { $_ -notin $migNames })
Add-Result 'ECR-001: migrations 0032-0037 present' ($missingEcrMig.Count -eq 0) ("missing: " + ($missingEcrMig -join ', '))

# --- ECR-003: corrected history capture -------------------------------------
# The ECR-001 capture function embedded 'NEW.<col>' tokens inside dynamic SQL
# (runtime failure: EXECUTE has no NEW/OLD bindings) and duplicated
# version_number in the INSERT list. ECR-003 ships an additive CREATE OR
# REPLACE (migration 0038) that binds values via jsonb_populate_record + USING.
$fixTxt = ''
foreach ($f in (Get-Files 'schema\06-functions')) {
    if ($f.Name -match '05_ecr_fix_capture_entity_history') { $fixTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'ECR-003: fix migration 0038 present' ('0038_ecr_fix_capture_history.sql' -in $migNames) 'additive CREATE OR REPLACE of capture_entity_history()'
$fixOk = ($fixTxt -match 'jsonb_populate_record\s*\(NULL::%I, \$1\)') -and
         ($fixTxt -match 'USING snapshot') -and
         (-not ($fixTxt -match 'format\(.*NEW\.%I')) -and
         ($fixTxt -notmatch 'ins_vals')
Add-Result 'ECR-003: corrected function binds values (jsonb_populate_record + USING), no NEW.* in dynamic SQL' $fixOk 'runtime defect eliminated'
# The actor-column mapping must never NULL-out the snapshot: to_jsonb(NULL)
# returns SQL NULL and jsonb_set(new_value := NULL) would wipe the whole jsonb.
# A missing created_by/updated_by must be mapped to JSON null via COALESCE.
$nullSafeMap = ($fixTxt -match 'COALESCE\s*\(\s*to_jsonb\s*\([^)]*\),\s*''null''::jsonb\)')
Add-Result 'ECR-003: changed_by mapping is NULL-safe (COALESCE to ''null''::jsonb, snapshot never nuked)' $nullSafeMap 'regression guard for the second live defect'
# Second live defect: BEFORE-capture inserts the history row before the entity
# row exists, so the original_entity_id FK must be deferred to COMMIT. 0039
# flips all 13 history original_entity_id FKs to DEFERRABLE INITIALLY DEFERRED.
$fkFixTxt = ''
foreach ($f in (Get-Files 'schema\03-constraints')) {
    if ($f.Name -match '11_ecr_fix_history_original_entity_fk') { $fkFixTxt = [System.IO.File]::ReadAllText($f.FullName) }
}
Add-Result 'ECR-003: FK-deferral migration 0039 present' ('0039_ecr_fix_history_original_entity_fk.sql' -in $migNames) 'additive DEFERRABLE INITIALLY DEFERRED fix for all 13 history FKs'
$deferCount = ([regex]::Matches($fkFixTxt, 'ALTER\s+CONSTRAINT\s+\w+_original_entity_id_fk\s+DEFERRABLE\s+INITIALLY\s+DEFERRED')).Count
Add-Result 'ECR-003: all 13 original_entity_id FKs made DEFERRABLE INITIALLY DEFERRED' ($deferCount -eq 13) ("deferral statements found: $deferCount")

# --- 6. Foreign key integrity ------------------------------------------------
$allTables = $tables
$fkLines = @()
foreach ($f in (Get-Files 'schema\03-constraints')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $fkLines += ([regex]::Matches($txt, 'REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)') | ForEach-Object { "{0}.{1}" -f $_.Groups[1].Value, $_.Groups[2].Value })
}
$badFk = @()
foreach ($fk in $fkLines) {
    $target = ($fk -split '\.')[0]
    if ($target -notin $allTables) { $badFk += "$fk -> missing table $target" }
}
Add-Result 'Constraints: every FK target table exists' ($badFk.Count -eq 0) ("fk targets: " + ($fkLines -join ', '))

# No CASCADE anywhere in DDL.
$cascadeHits = @()
foreach ($f in (Get-ChildItem -LiteralPath (Join-Path $root 'schema') -Recurse -Filter '*.sql')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    foreach ($m in [regex]::Matches($txt, 'ON\s+(DELETE|UPDATE)\s+CASCADE')) { $cascadeHits += "$($f.Name): $($m.Value)" }
}
Add-Result 'Constraints: no ON DELETE/UPDATE CASCADE' ($cascadeHits.Count -eq 0) ("hits: " + ($cascadeHits -join ', '))

# FK-supporting indexes exist for every FK column.
$fkCols = @()
foreach ($f in (Get-Files 'schema\03-constraints')) {
    $txt = [System.IO.File]::ReadAllText($f.FullName)
    $fkCols += ([regex]::Matches($txt, 'ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY\s*\(\s*(\w+)\s*\)') | ForEach-Object { $_.Groups[1].Value })
}
$indexTxt = ''
foreach ($f in (Get-Files 'schema\04-indexes')) { $indexTxt += [System.IO.File]::ReadAllText($f.FullName) }
$unindexedFk = @($fkCols | Where-Object { $indexTxt -notmatch ([regex]::Escape("($_ )")) -and $indexTxt -notmatch ([regex]::Escape("($_)")) })
Add-Result 'Indexes: every FK column indexed' ($unindexedFk.Count -eq 0) ("fk cols: " + ($fkCols -join ', '))

# --- 7. Naming and quality ---------------------------------------------------
$badIdentifier = @()
$allSqlText = ''
foreach ($f in (Get-ChildItem -LiteralPath (Join-Path $root 'schema') -Recurse -Filter '*.sql')) {
    $allSqlText += [System.IO.File]::ReadAllText($f.FullName) + "`n"
}
if ($allSqlText -match 'VARCHAR\s*\(|CHAR\s*\(') { $badIdentifier += 'varchar/char usage' }
# A column literally named desc would be a short/reserved identifier; the SQL
# keyword DESC (index/ORDER BY) is legitimate and must not be flagged.
if ($allSqlText -match '(?m)^\s*desc\s+(text|citext|uuid|bigint|integer|numeric|boolean|timestamptz|jsonb)') { $badIdentifier += 'reserved/short desc identifier' }
Add-Result 'Types: no VARCHAR(n)/CHAR(n), full names' ($badIdentifier.Count -eq 0) ("issues: " + ($badIdentifier -join ', '))

# Extensions declared in 0001 must cover citext usage in tables.
$extTxt = ''
foreach ($f in (Get-Files 'schema\00-extensions')) { $extTxt += [System.IO.File]::ReadAllText($f.FullName) }
$citextOk = ($extTxt -match 'citext') -and ($allSqlText -match '\bcitext\b')
Add-Result 'Extensions: citext enabled and used correctly' $citextOk 'citext in extensions + tables'

# --- 8. Circular dependency check (module-level) ------------------------------
# Tables do not reference each other at CREATE time; FKs are deferred to 0004+.
# Self-references are the only permitted 'cycle' (relationship_types,
# ingredient_categories, product_categories, every history table via
# previous_version_id, and entity_versions via previous_version_id).
$circular = $false
$selfRefs = @()
$permittedSelfRef = @('relationship_types','ingredient_categories','product_categories') + $historyTables + @('entity_versions')
foreach ($fk in $fkLines) {
    $target = ($fk -split '\.')[0]
    if ($target -in $permittedSelfRef) { $selfRefs += $target; continue }
}
Add-Result 'Dependency graph: no circular table dependencies' (-not $circular) ("FKs deferred to 0004+; only self-refs: " + ($selfRefs -join ', '))

# --- Report ----------------------------------------------------------------
Write-Host ''
Write-Host 'Foundation Layer validation results:'
Write-Host '-----------------------------------'
$failures = 0
foreach ($r in $results) {
    $mark = if ($r.Status -eq 'PASS') { '[PASS]' } else { '[FAIL]' }
    Write-Host ("{0} {1}" -f $mark, $r.Check)
    if ($r.Status -eq 'FAIL') {
        $failures++
        Write-Host ("      detail: {0}" -f $r.Detail)
    }
}
Write-Host '-----------------------------------'
Write-Host ("Summary: {0} checks, {1} passed, {2} failed" -f $results.Count, ($results.Count - $failures), $failures)
if ($failures -gt 0) { exit 1 }
exit 0
