// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnSzWf9_IWF9YqGV8vn--zVuQ5hqTjVs',
    appId: '1:322349985987:web:68397aa58954ffd1cc7276',
    messagingSenderId: '322349985987',
    projectId: 'fateen-app',
    authDomain: 'fateen-app.firebaseapp.com',
    storageBucket: 'fateen-app.firebasestorage.app',
    measurementId: 'G-RW5ZCSKDPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LIOITCopkBecV040Ph2qTJ9NT5pK9BA',
    appId: '1:322349985987:android:137f278a2ce05a41cc7276',
    messagingSenderId: '322349985987',
    projectId: 'fateen-app',
    storageBucket: 'fateen-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVzJQ5WHsYMJP0HZ5pNCq8vCphfEYBXk',
    appId: '1:322349985987:ios:2c2ad70f8f67870ccc7276',
    messagingSenderId: '322349985987',
    projectId: 'fateen-app',
    storageBucket: 'fateen-app.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJVzJQ5WHsYMJP0HZ5pNCq8vCphfEYBXk',
    appId: '1:322349985987:ios:2c2ad70f8f67870ccc7276',
    messagingSenderId: '322349985987',
    projectId: 'fateen-app',
    storageBucket: 'fateen-app.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOnSzWf9_IWF9YqGV8vn--zVuQ5hqTjVs',
    appId: '1:322349985987:web:4a445f85e2ea4335cc7276',
    messagingSenderId: '322349985987',
    projectId: 'fateen-app',
    authDomain: 'fateen-app.firebaseapp.com',
    storageBucket: 'fateen-app.firebasestorage.app',
    measurementId: 'G-9WTGNNWEEW',
  );
}
