-- =============================================================================
-- MIGRATION 0002 - foundation_enums
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 10 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\01_entity_status.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: entity_status
-- -----------------------------------------------------------------------------
-- Purpose:       Lifecycle of a governed entity (product, ingredient, brand, ...)
--                once it exists in the knowledge base. This is the PUBLISHED
--                lifecycle. The review/approval workflow state is tracked
--                separately by approval_status.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Governed entities are never hard-deleted; they progress through
--                a published lifecycle and may be deprecated or archived while
--                their version history remains intact.
-- Values:
--   draft       Being authored, not yet visible as published content.
--   active      Published and visible; governed by the review workflow.
--   inactive    Temporarily hidden from active views; history retained.
--   deprecated  Superseded; still resolvable and linked for integrity.
--   archived    Withdrawn from active use; retained only for history/audit.
-- =============================================================================
CREATE TYPE entity_status AS ENUM (
    'draft',
    'active',
    'inactive',
    'deprecated',
    'archived'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\02_approval_status.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: approval_status
-- -----------------------------------------------------------------------------
-- Purpose:       State of the governance review/approval workflow for a submitted
--                change or version. Distinct from entity_status (published
--                lifecycle) and from review_decision (the outcome of one review
--                action).
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Every governed change flows through this state machine so the
--                review history is fully reconstructable without redesign.
-- Values:
--   pending_review    Submitted, awaiting assignment/review start.
--   in_review         Actively under review.
--   changes_requested Reviewer requested changes; work has been sent back.
--   approved          Approved; the change is applied to the governed record.
--   rejected          Rejected; the change is not applied.
--   cancelled         Withdrawn by the submitter before a final decision.
-- =============================================================================
CREATE TYPE approval_status AS ENUM (
    'pending_review',
    'in_review',
    'changes_requested',
    'approved',
    'rejected',
    'cancelled'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\03_review_tier.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: review_tier
-- -----------------------------------------------------------------------------
-- Purpose:       Escalation tier that determines the reviewer qualifications and
--                consensus required before a change may be approved.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     The governance milestone assigns a tier per change based on
--                risk (e.g. allergens, restricted ingredients, source conflicts).
--                Tiers are ordered from least to most stringent.
-- Values:
--   automated   Machine validation only; no human reviewer. Reserved for
--               low-risk, high-confidence, mechanically verifiable changes.
--   standard    One qualified reviewer.
--   elevated    Additional scrutiny (senior reviewer and/or multiple reviewers).
--   expert      Requires subject-matter expertise in the affected domain.
--   consensus   Multiple expert reviewers must agree; used for high-impact data.
-- =============================================================================
CREATE TYPE review_tier AS ENUM (
    'automated',
    'standard',
    'elevated',
    'expert',
    'consensus'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\04_review_decision.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: review_decision
-- -----------------------------------------------------------------------------
-- Purpose:       Outcome recorded for ONE individual review action within the
--                approval workflow. The aggregate workflow state is tracked by
--                approval_status.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Recording per-action decisions (not just the final state) makes
--                the review trail auditable and reconstructable.
-- Values:
--   approved           Reviewer approved the change.
--   rejected           Reviewer rejected the change.
--   changes_requested  Reviewer returned the change for modification.
--   escalated          Reviewer escalated to a higher tier for decision.
-- =============================================================================
CREATE TYPE review_decision AS ENUM (
    'approved',
    'rejected',
    'changes_requested',
    'escalated'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\05_version_status.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: version_status
-- -----------------------------------------------------------------------------
-- Purpose:       Lifecycle of a single version of a governed entity within the
--                version-history system.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Version history is immutable: a version's status only ever moves
--                forward (draft -> pending_approval -> approved/rejected, then
--                approved -> superseded when a newer version takes over).
-- Values:
--   draft             Version is being composed, not submitted.
--   pending_approval  Submitted to the review workflow.
--   approved          Approved and applied as the current governed version.
--   rejected          Rejected; never becomes current.
--   superseded        Was approved but a newer version is now current.
-- =============================================================================
CREATE TYPE version_status AS ENUM (
    'draft',
    'pending_approval',
    'approved',
    'rejected',
    'superseded'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\06_confidence_band.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: confidence_band
-- -----------------------------------------------------------------------------
-- Purpose:       Discretized confidence on a governed fact or relationship,
--                derived from the numeric confidence_score.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Confidence is stored numerically (confidence_score, 0..1) for
--                computation and bucketed into bands for display, filtering, and
--                governance triage. Band boundaries are fixed by the architecture
--                and are half-open intervals [lower, upper).
-- Values (numeric range of confidence_score):
--   very_low   [0.00, 0.20)
--   low        [0.20, 0.40)
--   medium     [0.40, 0.60)
--   high       [0.60, 0.80)
--   very_high  [0.80, 1.00]
-- =============================================================================
CREATE TYPE confidence_band AS ENUM (
    'very_low',
    'low',
    'medium',
    'high',
    'very_high'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\07_translation_status.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: translation_status
-- -----------------------------------------------------------------------------
-- Purpose:       Lifecycle of a single translation row in the i18n layer.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Translation quality is governed independently of the source
--                content: a translation may be reviewed and approved while the
--                source entity is unchanged.
-- Values:
--   draft           Translation created, not yet finished.
--   in_progress     Translation being worked on.
--   pending_review  Translation submitted for review.
--   approved        Translation reviewed and approved for display.
--   rejected        Translation rejected; requires rework.
-- =============================================================================
CREATE TYPE translation_status AS ENUM (
    'draft',
    'in_progress',
    'pending_review',
    'approved',
    'rejected'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\08_candidate_status.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: candidate_status
-- -----------------------------------------------------------------------------
-- Purpose:       Lifecycle of a candidate record inside the production population
--                pipeline, BEFORE it becomes a governed entity. Candidate rows are
--                discovered, enriched, normalized, deduplicated, then promoted
--                into governed entities (or discarded/merged).
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Keeps ungoverned, raw pipeline state fully separate from the
--                governed knowledge base so low-quality data never leaks into
--                governed tables.
-- Values:
--   discovered      Raw record ingested; no processing yet.
--   enriched        Attribute/completeness enrichment applied.
--   normalized      Name/format normalization applied.
--   pending_review  Candidate ready for human or automated adjudication.
--   approved        Candidate accepted; promoted toward a governed entity.
--   merged          Candidate merged into an existing record; superseded.
--   discarded       Candidate rejected and retained only for audit.
-- =============================================================================
CREATE TYPE candidate_status AS ENUM (
    'discovered',
    'enriched',
    'normalized',
    'pending_review',
    'approved',
    'merged',
    'discarded'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\09_update_type.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: update_type
-- -----------------------------------------------------------------------------
-- Purpose:       Classifies the nature of a change recorded in version history.
-- Work orders:   Foundation Layer, work order #2 (enumerations).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     History entries must explain WHAT happened (update_type) in
--                addition to WHEN and BY WHOM, so the audit trail reads as a
--                narrative and supports reversion analysis.
-- Values:
--   created      A new entity or version was created.
--   modified     Existing content was changed.
--   published    An approved version was published to active state.
--   unpublished  An active record was taken out of active state.
--   deprecated   A record was marked deprecated.
--   archived     A record was archived.
--   merged       Records were merged; the losing record is referenced.
--   split        A record was split; the resulting records are referenced.
-- =============================================================================
CREATE TYPE update_type AS ENUM (
    'created',
    'modified',
    'published',
    'unpublished',
    'deprecated',
    'archived',
    'merged',
    'split'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\01-enums\10_unit_dimension.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Enum: unit_dimension
-- -----------------------------------------------------------------------------
-- Purpose:       Physical/measurement dimension that a unit of measure belongs to.
--                Used by the units lookup table to group units and by the future
--                unit-conversion layer to scope conversions.
-- Work orders:   Foundation Layer, work order #2 (enumerations). Required by the
--                units lookup table (work order #3).
-- Dependencies:  None.
-- Migration:     0002_foundation_enums.sql
-- Rule:          Internal immutable system state only; never governed business
--                knowledge (ADR-001 / ADR-007).
-- Rationale:     Classifying units by dimension makes conversion logic safe: a
--                conversion is only legal within a single dimension, and one base
--                unit per dimension is enforced by a partial unique index.
-- Values:
--   mass       Mass/weight (g, kg, mg, ...).
--   volume     Volume (ml, l, ...).
--   energy     Energy (kcal, kJ, ...).
--   temperature  Temperature (deg_c, deg_f).
--   count      Discrete countable items (piece, pack).
--   ratio      Dimensionless proportions (percent, ppm).
--   amount     Substance amount (mol, international units IU).
--   other      Any measure not covered above.
-- =============================================================================
CREATE TYPE unit_dimension AS ENUM (
    'mass',
    'volume',
    'energy',
    'temperature',
    'count',
    'ratio',
    'amount',
    'other'
);
