-- =============================================================================
-- MIGRATION 0003 - foundation_lookup_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 12 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\01_lifecycle_statuses.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: lifecycle_statuses
-- -----------------------------------------------------------------------------
-- Purpose:       Shared non-destructive lifecycle vocabulary for every governed
--                lookup/domain table: ACTIVE, DEPRECATED, ARCHIVED. Reference
--                rows are never hard-deleted; they progress through this status
--                instead (ADR-006 / ADR-008).
-- Work orders:   Foundation Layer, work order #3 (lookup tables). Architecture
--                Authority directive #007 (explicit lifecycle on lookup tables).
-- Dependencies:  Extension citext (0001).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     status_id on every lookup table is the authoritative lifecycle
--                field (business logic must never depend solely on a boolean).
--                This small, closed reference uses a BIGINT identity key per the
--                Architecture Authority directive - the single exception to the
--                UUID-key convention (ADR-008). Future states (PENDING,
--                DISABLED, SUPERSEDED) are data inserts, never schema changes.
-- Columns:
--   code           Stable machine reference: ACTIVE, DEPRECATED, ARCHIVED.
-- =============================================================================
CREATE TABLE lifecycle_statuses (
    id             bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT lifecycle_statuses_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT lifecycle_statuses_code_unique
        UNIQUE (code),
    CONSTRAINT lifecycle_statuses_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE lifecycle_statuses IS
    'Shared non-destructive lifecycle vocabulary (ACTIVE, DEPRECATED, ARCHIVED); the status authority for every lookup table.';
COMMENT ON COLUMN lifecycle_statuses.id IS
    'BIGINT identity key (Architecture Authority directive; exception to the UUID convention, ADR-008).';
COMMENT ON COLUMN lifecycle_statuses.code IS
    'Stable machine reference: ACTIVE, DEPRECATED, ARCHIVED; future states are data inserts.';
COMMENT ON COLUMN lifecycle_statuses.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\02_languages.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: languages
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of the languages the platform supports for
--                content and translation. Arabic and English ship from day one;
--                GCC and global languages are added by governance, not by schema
--                migration (see ADR-001).
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Languages are governed data. The code column is the stable,
--                case-insensitive reference that future translation and content
--                tables will foreign-key.
-- Columns:
--   code          ISO 639-1 two-letter code where available; BCP-47 tag for
--                 variants and regional scripts.
--   name          Canonical English working name (display translations arrive
--                 with the i18n milestone).
--   native_name   Endonym: the language's name in itself (e.g. العربية).
--   is_rtl        True for right-to-left scripts (Arabic).
-- =============================================================================
CREATE TABLE languages (
    id           uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code         citext       NOT NULL,
    name         text         NOT NULL,
    native_name  text         NOT NULL,
    is_rtl       boolean      NOT NULL DEFAULT false,
    status_id    bigint        NOT NULL,
    version_number  integer   NOT NULL DEFAULT 1,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    deleted_at   timestamptz  NULL,

    CONSTRAINT languages_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT languages_code_check
        CHECK (char_length(code) BETWEEN 2 AND 10),
    CONSTRAINT languages_code_unique
        UNIQUE (code)
);

COMMENT ON TABLE languages IS
    'Governed registry of supported platform languages (Arabic + English day one).';
COMMENT ON COLUMN languages.code IS
    'ISO 639-1 two-letter code where available; BCP-47 tag for variants.';
COMMENT ON COLUMN languages.name IS
    'Canonical English working name; display translations arrive with the i18n milestone.';
COMMENT ON COLUMN languages.native_name IS
    'Endonym of the language in its own script (e.g. العربية).';
COMMENT ON COLUMN languages.is_rtl IS
    'True for right-to-left scripts.';
COMMENT ON COLUMN languages.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\03_countries.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: countries
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of countries, keyed to ISO 3166-1. Supports
--                the Saudi-first deployment and the GCC/global expansion phases.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Countries scope data sources and future market content. The
--                ISO 3166-1 codes are stored in their canonical forms and are
--                unique and case-insensitive.
-- Columns:
--   code           ISO 3166-1 alpha-2 (SA, AE, US, ...).
--   alpha_3        ISO 3166-1 alpha-3 (SAU, ARE, USA, ...).
--   numeric_code   ISO 3166-1 numeric three-digit code (682, 784, 840, ...).
--   is_gcc_member  True for Gulf Cooperation Council member states; feeds the
--                  GCC expansion phase.
-- =============================================================================
CREATE TABLE countries (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    alpha_3        citext       NOT NULL,
    numeric_code   text         NOT NULL,
    name           text         NOT NULL,
    is_gcc_member  boolean      NOT NULL DEFAULT false,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT countries_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT countries_code_check
        CHECK (code ~ '^[A-Za-z]{2}$'),
    CONSTRAINT countries_alpha_3_check
        CHECK (alpha_3 ~ '^[A-Za-z]{3}$'),
    CONSTRAINT countries_numeric_code_check
        CHECK (numeric_code ~ '^[0-9]{3}$'),
    CONSTRAINT countries_code_unique
        UNIQUE (code),
    CONSTRAINT countries_alpha_3_unique
        UNIQUE (alpha_3),
    CONSTRAINT countries_numeric_code_unique
        UNIQUE (numeric_code)
);

COMMENT ON TABLE countries IS
    'Governed registry of countries (ISO 3166-1), Saudi-first with GCC/global scope.';
COMMENT ON COLUMN countries.code IS
    'ISO 3166-1 alpha-2 country code.';
COMMENT ON COLUMN countries.alpha_3 IS
    'ISO 3166-1 alpha-3 country code.';
COMMENT ON COLUMN countries.numeric_code IS
    'ISO 3166-1 numeric three-digit country code.';
COMMENT ON COLUMN countries.is_gcc_member IS
    'True for Gulf Cooperation Council member states; feeds the GCC expansion phase.';
COMMENT ON COLUMN countries.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\04_units.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: units
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of units of measure (mass, volume, energy, ...)
--                referenced by future nutrition and quantity data.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum unit_dimension (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Units are grouped by dimension (unit_dimension) so the future
--                conversion layer is provably dimension-safe. Exactly one base
--                unit per dimension is enforced by a partial unique index
--                (04-indexes). A unit may carry a code distinct from its display
--                symbol (e.g. code 'ug', symbol 'µg').
-- Columns:
--   code          Stable machine reference, based on the international symbol
--                 where possible. Not an abbreviation: e.g. 'g' is the SI symbol
--                 for gram.
--   name          Canonical English name.
--   symbol        Display symbol.
--   dimension     Physical dimension (unit_dimension).
--   is_base_unit  True for the canonical base unit within its dimension, used
--                 as the conversion anchor (one per dimension).
-- =============================================================================
CREATE TABLE units (
    id            uuid             NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code          citext           NOT NULL,
    name          text             NOT NULL,
    symbol        text             NOT NULL,
    dimension     unit_dimension   NOT NULL,
    is_base_unit  boolean          NOT NULL DEFAULT false,
    status_id     bigint           NOT NULL,
    version_number  integer        NOT NULL DEFAULT 1,
    created_at    timestamptz      NOT NULL DEFAULT now(),
    updated_at    timestamptz      NOT NULL DEFAULT now(),
    deleted_at    timestamptz      NULL,

    CONSTRAINT units_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT units_code_unique
        UNIQUE (code),
    CONSTRAINT units_symbol_unique
        UNIQUE (symbol)
);

COMMENT ON TABLE units IS
    'Governed registry of units of measure, grouped by physical dimension.';
COMMENT ON COLUMN units.code IS
    'Stable machine reference based on the international symbol (e.g. g, kg, kcal).';
COMMENT ON COLUMN units.name IS
    'Canonical English name (e.g. gram).';
COMMENT ON COLUMN units.symbol IS
    'Display symbol (may differ from code, e.g. code ug / symbol µg).';
COMMENT ON COLUMN units.dimension IS
    'Physical dimension of the unit; conversions are only legal within one dimension.';
COMMENT ON COLUMN units.is_base_unit IS
    'Designates the canonical base unit for a dimension (exactly one per dimension).';
COMMENT ON COLUMN units.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\05_package_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: package_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of packaging types (can, bottle, jar, pouch,
--                carton, ...) used by product packaging data.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Packaging vocabulary is reference data; new types are added by
--                governance, not schema migration (see ADR-001).
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE package_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT package_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT package_types_code_unique
        UNIQUE (code),
    CONSTRAINT package_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE package_types IS
    'Governed registry of packaging types.';
COMMENT ON COLUMN package_types.display_order IS
    'Stable ordering for reference pickers; non-negative.';
COMMENT ON COLUMN package_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\06_barcode_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: barcode_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of barcode symbologies (GTIN-8/12/13/14,
--                GS1-128, QR, DataMatrix, ...) for product barcode data.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Barcode symbologies are reference data (see ADR-001). The
--                digit_length column records the fixed numeric payload length
--                where one exists, enabling payload validation in the population
--                pipeline.
-- Columns:
--   code           Stable machine reference (gs1 naming, e.g. gtin_13).
--   digit_length   Fixed numeric payload length; NULL for 2D/matrix symbologies.
-- =============================================================================
CREATE TABLE barcode_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    digit_length   smallint     NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT barcode_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT barcode_types_code_unique
        UNIQUE (code),
    CONSTRAINT barcode_types_digit_length_check
        CHECK (digit_length IS NULL OR digit_length > 0),
    CONSTRAINT barcode_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE barcode_types IS
    'Governed registry of barcode symbologies.';
COMMENT ON COLUMN barcode_types.digit_length IS
    'Fixed numeric payload length for GTIN family; NULL for 2D/matrix types.';
COMMENT ON COLUMN barcode_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\07_image_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: image_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of product image categories (primary, front,
--                back, nutrition facts panel, ingredients list, packaging,
--                logo, barcode, ...).
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Image categories are reference data (see ADR-001). They exist
--                now so the images milestone can reference them without redesign.
-- =============================================================================
CREATE TABLE image_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT image_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT image_types_code_unique
        UNIQUE (code),
    CONSTRAINT image_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE image_types IS
    'Governed registry of product image categories.';
COMMENT ON COLUMN image_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\08_relationship_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: relationship_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of knowledge-graph edge types between governed
--                entities (contains_ingredient, similar_to, substitutable_for,
--                ...). Seeded by governance; extensible without schema changes.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     The knowledge graph milestone references this table for all
--                edges. is_directional expresses whether subject->object order is
--                meaningful; inverse_type_id links a type to its paired inverse
--                (e.g. contains_ingredient <-> is_ingredient_of). The
--                self-referential foreign key is applied in 03-constraints.
-- Columns:
--   code             Stable machine reference (snake_case).
--   is_directional   True when subject->object order matters.
--   inverse_type_id  Self-reference to the paired inverse relationship type.
-- =============================================================================
CREATE TABLE relationship_types (
    id                uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code              citext       NOT NULL,
    name              text         NOT NULL,
    description       text         NULL,
    is_directional    boolean      NOT NULL DEFAULT true,
    inverse_type_id   uuid         NULL,
    display_order     integer      NOT NULL DEFAULT 0,
    status_id         bigint        NOT NULL,
    version_number    integer      NOT NULL DEFAULT 1,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now(),
    deleted_at        timestamptz  NULL,

    CONSTRAINT relationship_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT relationship_types_code_unique
        UNIQUE (code),
    CONSTRAINT relationship_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE relationship_types IS
    'Governed registry of knowledge-graph relationship types between entities.';
COMMENT ON COLUMN relationship_types.is_directional IS
    'True when subject->object order is meaningful (paired with inverse_type_id).';
COMMENT ON COLUMN relationship_types.inverse_type_id IS
    'Self-reference to the paired inverse relationship type; NULL when symmetric.';
COMMENT ON COLUMN relationship_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\09_source_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: source_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of data-source categories (manual entry, API
--                integration, file import, partner feed, regulatory, scientific
--                literature, community). Classifies every data_sources row.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Source categories are reference data (see ADR-001). They exist
--                now so data_sources and, later, the confidence/governance
--                milestone can reference them without redesign.
-- =============================================================================
CREATE TABLE source_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT source_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT source_types_code_unique
        UNIQUE (code),
    CONSTRAINT source_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE source_types IS
    'Governed registry of data-source categories.';
COMMENT ON COLUMN source_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\10_source_priorities.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: source_priorities
-- -----------------------------------------------------------------------------
-- Purpose:       Governed trust/priority scale for data sources, used in conflict
--                resolution and confidence derivation across the pipeline.
-- Work orders:   Foundation Layer, work order #3 (lookup tables).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Priority is a stable ordinal scale; rank makes the ordering
--                explicit and query-safe instead of relying on insertion order.
-- Columns:
--   rank  Ascending severity: 1 = lowest priority, higher value wins conflicts.
-- =============================================================================
CREATE TABLE source_priorities (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    rank           smallint     NOT NULL,
    description    text         NULL,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT source_priorities_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT source_priorities_code_unique
        UNIQUE (code),
    CONSTRAINT source_priorities_rank_unique
        UNIQUE (rank),
    CONSTRAINT source_priorities_rank_check
        CHECK (rank BETWEEN 1 AND 99)
);

COMMENT ON TABLE source_priorities IS
    'Governed trust/priority scale for data sources.';
COMMENT ON COLUMN source_priorities.rank IS
    'Ascending ordinal: higher rank wins conflicts; bounded to 1..99.';
COMMENT ON COLUMN source_priorities.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\11_data_sources.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: data_sources
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of concrete data sources (e.g. a national
--                authority, a partner feed, a scientific dataset, manual entry)
--                from which facts enter the knowledge base. Every governed fact
--                in later milestones will carry source_id and confidence_score
--                referencing this registry.
-- Work orders:   Foundation Layer, work order #3 (lookup tables). The
--                governance/confidence milestone (future) depends on this table.
-- Dependencies:  Extension citext (0001). Enum set (0002). Tables source_types,
--                source_priorities, countries (all in 0003). Foreign keys are
--                applied in 0004 (03-constraints).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     A source is classified by type and priority and may be scoped
--                to a country jurisdiction (NULL = global/unspecified).
--                is_verified marks institutional sources the pipeline may trust
--                without individual human review of every record.
-- Columns:
--   source_type_id   Category of the source (FK source_types).
--   priority_id      Trust priority for conflict resolution (FK source_priorities).
--   country_id       Jurisdictional scope; NULL = global (FK countries).
--   is_verified      True for institutionally trusted sources.
-- =============================================================================
CREATE TABLE data_sources (
    id              uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code            citext       NOT NULL,
    name            text         NOT NULL,
    description     text         NULL,
    source_type_id  uuid         NOT NULL,
    priority_id     uuid         NOT NULL,
    country_id      uuid         NULL,
    is_verified     boolean      NOT NULL DEFAULT false,
    status_id       bigint        NOT NULL,
    version_number  integer      NOT NULL DEFAULT 1,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    deleted_at      timestamptz  NULL,

    CONSTRAINT data_sources_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT data_sources_code_unique
        UNIQUE (code)
);

COMMENT ON TABLE data_sources IS
    'Governed registry of concrete data sources feeding the knowledge base.';
COMMENT ON COLUMN data_sources.source_type_id IS
    'Category of the source (foreign key to source_types).';
COMMENT ON COLUMN data_sources.priority_id IS
    'Trust priority for conflict resolution (foreign key to source_priorities).';
COMMENT ON COLUMN data_sources.country_id IS
    'Jurisdictional scope; NULL means global/unspecified (foreign key to countries).';
COMMENT ON COLUMN data_sources.is_verified IS
    'True for institutionally trusted sources that may bypass per-record human review.';
COMMENT ON COLUMN data_sources.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\12_health_flag_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: health_flag_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of health/risk flag classes (allergen,
--                intolerance, restricted_ingredient, recall, contamination,
--                not_suitable_for, other) attached to products and ingredients.
-- Work orders:   Foundation Layer, work order #3 (lookup tables). Refactor per
--                Architecture Authority decision: formerly the health_flag_type
--                ENUM; business knowledge must live in data, not in ENUM types
--                (ADR-001 / ADR-007).
-- Dependencies:  Extension citext (0001). Enum set (0002).
-- Migration:     0003_foundation_lookup_tables.sql
-- Rationale:     Health-flag classes are governed, evolving business vocabulary:
--                new classes of risk, translations (Arabic/English), deprecation
--                and governance all apply. Modeling them as a lookup table means
--                future additions are data inserts, never ALTER TYPE.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE health_flag_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT health_flag_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT health_flag_types_code_unique
        UNIQUE (code),
    CONSTRAINT health_flag_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE health_flag_types IS
    'Governed registry of health/risk flag classes (business knowledge, not ENUM).';
COMMENT ON COLUMN health_flag_types.code IS
    'Stable machine reference (snake_case), e.g. allergen, recall.';
COMMENT ON COLUMN health_flag_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';
