-- =============================================================================
-- MIGRATION 0004 - foundation_lookup_constraints
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 3 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\03-constraints\01_relationship_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Constraints: relationship_types
-- -----------------------------------------------------------------------------
-- Purpose:       Cross-row integrity for the relationship_types registry: the
--                self-referential inverse link must point at a real, distinct
--                row, and symmetric types must not declare an inverse.
-- Work orders:   Foundation Layer, work orders #5 (constraints) and #3.
-- Dependencies:  Table relationship_types (0003). Runs after all tables exist.
-- Migration:     0004_foundation_lookup_constraints.sql
-- Rationale:     A self-referencing foreign key cannot be declared inside the
--                table's CREATE TABLE (the table does not exist yet); it is
--                applied here after the table is committed.
-- =============================================================================
ALTER TABLE relationship_types
    ADD CONSTRAINT relationship_types_inverse_type_id_fk
        FOREIGN KEY (inverse_type_id)
        REFERENCES relationship_types (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

-- A relationship type must not be its own inverse.
ALTER TABLE relationship_types
    ADD CONSTRAINT relationship_types_inverse_not_self_check
        CHECK (inverse_type_id IS NULL OR inverse_type_id <> id);

-- Symmetric types (is_directional = false) have no inverse by definition.
ALTER TABLE relationship_types
    ADD CONSTRAINT relationship_types_symmetric_no_inverse_check
        CHECK (is_directional OR inverse_type_id IS NULL);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\03-constraints\02_data_sources.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Constraints: data_sources
-- -----------------------------------------------------------------------------
-- Purpose:       Referential integrity from data_sources to its classification
--                and jurisdiction lookups. No cascade anywhere: a referenced
--                lookup cannot be removed while sources depend on it.
-- Work orders:   Foundation Layer, work orders #5 (constraints) and #3.
-- Dependencies:  Tables data_sources, source_types, source_priorities,
--                countries (all in 0003). Runs after all tables exist.
-- Migration:     0004_foundation_lookup_constraints.sql
-- Rationale:     Foreign keys are applied here, after every referenced table is
--                committed, keeping 03-constraints the single home for
--                cross-table integrity (see sql_conventions.md).
-- =============================================================================
ALTER TABLE data_sources
    ADD CONSTRAINT data_sources_source_type_id_fk
        FOREIGN KEY (source_type_id)
        REFERENCES source_types (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE data_sources
    ADD CONSTRAINT data_sources_priority_id_fk
        FOREIGN KEY (priority_id)
        REFERENCES source_priorities (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE data_sources
    ADD CONSTRAINT data_sources_country_id_fk
        FOREIGN KEY (country_id)
        REFERENCES countries (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\03-constraints\03_lookup_status_fks.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Constraints: lookup table lifecycle statuses
-- -----------------------------------------------------------------------------
-- Purpose:       Every governed lookup table's status_id references the shared
--                lifecycle_statuses registry (ADR-008). No cascade anywhere: a
--                lifecycle status cannot be removed while any lookup row uses it.
-- Work orders:   Foundation Layer, work orders #5 (constraints) and #3.
--                Architecture Authority directive #007.
-- Dependencies:  Tables lifecycle_statuses and all 11 lookup tables (0003).
--                Runs after all tables exist.
-- Migration:     0004_foundation_lookup_constraints.sql
-- Rationale:     Cross-table integrity is applied here, after every referenced
--                table is committed (see sql_conventions.md).
-- =============================================================================
ALTER TABLE languages
    ADD CONSTRAINT languages_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE countries
    ADD CONSTRAINT countries_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE units
    ADD CONSTRAINT units_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE package_types
    ADD CONSTRAINT package_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE barcode_types
    ADD CONSTRAINT barcode_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE image_types
    ADD CONSTRAINT image_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE relationship_types
    ADD CONSTRAINT relationship_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE source_types
    ADD CONSTRAINT source_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE source_priorities
    ADD CONSTRAINT source_priorities_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE data_sources
    ADD CONSTRAINT data_sources_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;

ALTER TABLE health_flag_types
    ADD CONSTRAINT health_flag_types_status_id_fk
        FOREIGN KEY (status_id)
        REFERENCES lifecycle_statuses (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;
