-- =============================================================================
-- MIGRATION 0005 - foundation_lookup_indexes
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 4 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\04-indexes\01_units.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Indexes: units
-- -----------------------------------------------------------------------------
-- Purpose:       Enforce exactly one base unit per dimension.
-- Work orders:   Foundation Layer, work order #6 (indexes).
-- Dependencies:  Table units (0003). Runs after tables and constraints.
-- Migration:     0005_foundation_lookup_indexes.sql
-- Rationale:     The future unit-conversion layer anchors conversions on the base
--                unit of a dimension. A partial unique index on (dimension)
--                restricted to base units is the invariant that guarantees a
--                single, unambiguous anchor.
-- =============================================================================
CREATE UNIQUE INDEX units_one_base_unit_per_dimension_idx
    ON units (dimension)
    WHERE is_base_unit;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\04-indexes\02_relationship_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Indexes: relationship_types
-- -----------------------------------------------------------------------------
-- Purpose:       Index the self-referential inverse link.
-- Work orders:   Foundation Layer, work order #6 (indexes).
-- Dependencies:  Table relationship_types (0003) and its constraints (0004).
-- Migration:     0005_foundation_lookup_indexes.sql
-- Rationale:     PostgreSQL does not automatically index foreign-key columns.
--                inverse_type_id is queried to resolve inverse relationships, so
--                it is indexed here.
-- =============================================================================
CREATE INDEX relationship_types_inverse_type_id_idx
    ON relationship_types (inverse_type_id)
    WHERE inverse_type_id IS NOT NULL;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\04-indexes\03_data_sources.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Indexes: data_sources
-- -----------------------------------------------------------------------------
-- Purpose:       Index all foreign-key columns of data_sources.
-- Work orders:   Foundation Layer, work order #6 (indexes).
-- Dependencies:  Table data_sources (0003) and its constraints (0004).
-- Migration:     0005_foundation_lookup_indexes.sql
-- Rationale:     PostgreSQL does not automatically index foreign-key columns.
--                Sources are filtered by category, priority, and jurisdiction in
--                governance queries, so each FK column is indexed. source_type_id
--                and priority_id are NOT NULL, so full indexes; country_id is
--                nullable, so a partial index that skips NULLs.
-- =============================================================================
CREATE INDEX data_sources_source_type_id_idx
    ON data_sources (source_type_id);

CREATE INDEX data_sources_priority_id_idx
    ON data_sources (priority_id);

CREATE INDEX data_sources_country_id_idx
    ON data_sources (country_id)
    WHERE country_id IS NOT NULL;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\04-indexes\04_lookup_statuses.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Indexes: lookup table lifecycle statuses
-- -----------------------------------------------------------------------------
-- Purpose:       Index status_id on every lookup table (PostgreSQL does not
--                index foreign-key columns automatically).
-- Work orders:   Foundation Layer, work order #6 (indexes). Architecture
--                Authority directive #007.
-- Dependencies:  Tables and constraints from 0003/0004.
-- Migration:     0005_foundation_lookup_indexes.sql
-- Rationale:     Status is the primary filtering dimension for reference data
--                (active / deprecated / archived), so each status_id column is
--                indexed. status_id is NOT NULL everywhere, so full indexes.
-- =============================================================================
CREATE INDEX languages_status_id_idx
    ON languages (status_id);

CREATE INDEX countries_status_id_idx
    ON countries (status_id);

CREATE INDEX units_status_id_idx
    ON units (status_id);

CREATE INDEX package_types_status_id_idx
    ON package_types (status_id);

CREATE INDEX barcode_types_status_id_idx
    ON barcode_types (status_id);

CREATE INDEX image_types_status_id_idx
    ON image_types (status_id);

CREATE INDEX relationship_types_status_id_idx
    ON relationship_types (status_id);

CREATE INDEX source_types_status_id_idx
    ON source_types (status_id);

CREATE INDEX source_priorities_status_id_idx
    ON source_priorities (status_id);

CREATE INDEX data_sources_status_id_idx
    ON data_sources (status_id);

CREATE INDEX health_flag_types_status_id_idx
    ON health_flag_types (status_id);
