-- =============================================================================
-- MIGRATION 0006 - foundation_functions_and_triggers
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 2 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\06-functions\01_set_updated_at.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Function: set_updated_at()
-- -----------------------------------------------------------------------------
-- Purpose:       Single shared trigger function that stamps updated_at = now()
--                on every UPDATE of tables that carry the audit lifecycle columns.
-- Work orders:   Foundation Layer, work order #4 (governance support).
-- Dependencies:  None (plpgsql is built in). Called by triggers in 07-triggers.
-- Migration:     0006_foundation_functions_and_triggers.sql
-- Rationale:     updated_at is maintained by the database so no application code
--                can forget it. One function serves every table, keeping the
--                behavior consistent and reviewable.
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
    'Sets updated_at = now() on UPDATE; wired to every audit-carrying table.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\01_lookup_tables_updated_at.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: lookup tables updated_at
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared set_updated_at() function to every lookup table
--                carrying the audit lifecycle columns.
-- Work orders:   Foundation Layer, work order #4 (governance support).
-- Dependencies:  Function set_updated_at() (06-functions, same migration).
--                Lookup tables (0003).
-- Migration:     0006_foundation_functions_and_triggers.sql
-- Rationale:     Every table with updated_at must stamp it on UPDATE. Declaring
--                one trigger per table here keeps the rule explicit and auditable.
-- =============================================================================
CREATE TRIGGER languages_set_updated_at
    BEFORE UPDATE ON languages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER countries_set_updated_at
    BEFORE UPDATE ON countries
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER units_set_updated_at
    BEFORE UPDATE ON units
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER package_types_set_updated_at
    BEFORE UPDATE ON package_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER barcode_types_set_updated_at
    BEFORE UPDATE ON barcode_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER image_types_set_updated_at
    BEFORE UPDATE ON image_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER relationship_types_set_updated_at
    BEFORE UPDATE ON relationship_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER source_types_set_updated_at
    BEFORE UPDATE ON source_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER source_priorities_set_updated_at
    BEFORE UPDATE ON source_priorities
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER data_sources_set_updated_at
    BEFORE UPDATE ON data_sources
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER health_flag_types_set_updated_at
    BEFORE UPDATE ON health_flag_types
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER lifecycle_statuses_set_updated_at
    BEFORE UPDATE ON lifecycle_statuses
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
