-- =============================================================================
-- MIGRATION 0008 - foundation_reference_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 10 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\13_regions.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: regions
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of geopolitical regions (GCC, MENA, Europe,
--                North America, ...) that scope market and expansion content.
--                Flat today with no nested hierarchy; future country-to-region
--                links arrive with the market-scoping milestone.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Regions are governed, evolving business vocabulary: they are
--                translated, reordered, deprecated and governed over time. A
--                lookup table means future additions are data inserts, never
--                schema changes. The Saudi-first and GCC/global expansion phases
--                use these regions to scope market content.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE regions (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT regions_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT regions_code_unique
        UNIQUE (code),
    CONSTRAINT regions_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE regions IS
    'Governed registry of geopolitical regions (GCC, MENA, Europe, ...) for market scoping.';
COMMENT ON COLUMN regions.code IS
    'Stable machine reference (snake_case), e.g. gcc, mena, europe.';
COMMENT ON COLUMN regions.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\14_ingredient_categories.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_categories
-- -----------------------------------------------------------------------------
-- Purpose:       Governed, hierarchical taxonomy of ingredient categories
--                (whole, additive, sweetener, preservative, ...). A row may nest
--                under one parent (parent_id) to form a tree; taxonomy roots
--                have NULL parent. The self-foreign key is applied in
--                03-constraints (the table must exist before it references
--                itself).
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Ingredient categories are governed, evolving business
--                vocabulary: translated, reordered, deprecated and governed over
--                time. A bounded parent_id hierarchy gives a clean taxonomy
--                without a separate graph table; future additions are data
--                inserts, never schema changes.
-- Columns:
--   code           Stable machine reference (snake_case).
--   parent_id      Optional parent category (self-reference); NULL for roots.
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE ingredient_categories (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    parent_id      uuid         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT ingredient_categories_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_categories_code_unique
        UNIQUE (code),
    CONSTRAINT ingredient_categories_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE ingredient_categories IS
    'Governed hierarchical taxonomy of ingredient categories (self-referencing parent_id).';
COMMENT ON COLUMN ingredient_categories.code IS
    'Stable machine reference (snake_case).';
COMMENT ON COLUMN ingredient_categories.parent_id IS
    'Optional parent category (self-reference); NULL for taxonomy roots.';
COMMENT ON COLUMN ingredient_categories.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\15_product_categories.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_categories
-- -----------------------------------------------------------------------------
-- Purpose:       Governed, hierarchical taxonomy of product categories
--                (beverages, dairy, snacks, baby_food, ...). A row may nest under
--                one parent (parent_id) to form a tree; taxonomy roots have NULL
--                parent. The self-foreign key is applied in 03-constraints (the
--                table must exist before it references itself).
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Product categories are governed, evolving business vocabulary:
--                translated, reordered, deprecated and governed over time. A
--                bounded parent_id hierarchy gives a clean taxonomy without a
--                separate graph table; future additions are data inserts, never
--                schema changes.
-- Columns:
--   code           Stable machine reference (snake_case).
--   parent_id      Optional parent category (self-reference); NULL for roots.
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE product_categories (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    parent_id      uuid         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT product_categories_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_categories_code_unique
        UNIQUE (code),
    CONSTRAINT product_categories_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE product_categories IS
    'Governed hierarchical taxonomy of product categories (self-referencing parent_id).';
COMMENT ON COLUMN product_categories.code IS
    'Stable machine reference (snake_case).';
COMMENT ON COLUMN product_categories.parent_id IS
    'Optional parent category (self-reference); NULL for taxonomy roots.';
COMMENT ON COLUMN product_categories.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\16_allergen_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: allergen_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of allergen classes (gluten, crustaceans,
--                eggs, fish, peanuts, soy, milk, tree_nuts, sesame, sulfites,
--                ...) attached to products and ingredients for compliance
--                display and filtering.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Allergen classes are governed, evolving business vocabulary:
--                new regulated allergens, translations, deprecation and
--                governance all apply. Modeling them as a lookup table means
--                future additions are data inserts, never ALTER TYPE.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE allergen_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT allergen_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT allergen_types_code_unique
        UNIQUE (code),
    CONSTRAINT allergen_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE allergen_types IS
    'Governed registry of allergen classes (business knowledge, not ENUM).';
COMMENT ON COLUMN allergen_types.code IS
    'Stable machine reference (snake_case), e.g. gluten, tree_nuts, sesame.';
COMMENT ON COLUMN allergen_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\17_nutrition_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: nutrition_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of nutrition fact types (energy, protein,
--                total_fat, saturated_fat, carbohydrate, sugars, fiber, sodium,
--                ...) referenced by future per-100g / per-serving fact rows.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Nutrition fact types are governed business vocabulary: labels
--                and regulations evolve, translations apply, and facts must not
--                be coupled to a frozen ENUM (ADR-007). New fact types are data
--                inserts, never schema changes. Values are recorded in `units`
--                by the future nutrition milestone.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE nutrition_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT nutrition_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT nutrition_types_code_unique
        UNIQUE (code),
    CONSTRAINT nutrition_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE nutrition_types IS
    'Governed registry of nutrition fact types (business knowledge, not ENUM).';
COMMENT ON COLUMN nutrition_types.code IS
    'Stable machine reference (snake_case), e.g. energy, protein, sodium.';
COMMENT ON COLUMN nutrition_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\18_regulatory_authorities.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: regulatory_authorities
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of regulatory and standard authorities
--                (sfda, gso, efsa, fda, codex_alimentarius, ...) whose rules and
--                publications are cited as evidence by governed facts.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Authorities are governed, evolving business vocabulary: new
--                bodies, translations, deprecation and governance are data
--                inserts, never schema changes. Authorities anchor the
--                provenance of regulatory evidence in the evidence milestone.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE regulatory_authorities (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT regulatory_authorities_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT regulatory_authorities_code_unique
        UNIQUE (code),
    CONSTRAINT regulatory_authorities_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE regulatory_authorities IS
    'Governed registry of regulatory and standard authorities (sfda, efsa, codex, ...).';
COMMENT ON COLUMN regulatory_authorities.code IS
    'Stable machine reference (snake_case), e.g. sfda, gso, efsa, codex_alimentarius.';
COMMENT ON COLUMN regulatory_authorities.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\19_evidence_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: evidence_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of evidence kinds that back governed facts
--                (scientific_study, regulatory_document, label_image,
--                manufacturer_statement, user_report, ...).
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Evidence kinds are governed, evolving business vocabulary:
--                translated, reordered, deprecated and governed over time. New
--                kinds are data inserts, never schema changes. Future fact rows
--                cite evidence_type for provenance and confidence weighting.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE evidence_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT evidence_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT evidence_types_code_unique
        UNIQUE (code),
    CONSTRAINT evidence_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE evidence_types IS
    'Governed registry of evidence kinds that back governed facts.';
COMMENT ON COLUMN evidence_types.code IS
    'Stable machine reference (snake_case), e.g. scientific_study, label_image.';
COMMENT ON COLUMN evidence_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\20_role_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: role_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of platform user roles (admin, editor,
--                reviewer, expert, analyst, ...) used by future access control
--                and review-workflow authorization.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Roles are governed, evolving business vocabulary: translated,
--                reordered, deprecated and governed over time. New roles are
--                data inserts, never schema changes. The authorization layer
--                assigns permissions to roles in a later milestone.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE role_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT role_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT role_types_code_unique
        UNIQUE (code),
    CONSTRAINT role_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE role_types IS
    'Governed registry of platform user roles (admin, editor, reviewer, expert, ...).';
COMMENT ON COLUMN role_types.code IS
    'Stable machine reference (snake_case), e.g. admin, editor, reviewer, expert.';
COMMENT ON COLUMN role_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\21_permission_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: permission_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of permission classes (read, write, approve,
--                manage, audit, ...) that the future authorization layer assigns
--                to role_types.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Permissions are governed, evolving business vocabulary:
--                translated, reordered, deprecated and governed over time. New
--                permissions are data inserts, never schema changes. The
--                role-permission matrix is built in the authorization milestone.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE permission_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT permission_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT permission_types_code_unique
        UNIQUE (code),
    CONSTRAINT permission_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE permission_types IS
    'Governed registry of permission classes (read, write, approve, manage, ...).';
COMMENT ON COLUMN permission_types.code IS
    'Stable machine reference (snake_case), e.g. read, write, approve, audit.';
COMMENT ON COLUMN permission_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\22_audit_event_types.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: audit_event_types
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of audit event classes (created, updated,
--                status_changed, merged, deprecated, restored, exported, ...)
--                recorded by the future audit trail.
-- Work orders:   Mission 02: Foundation Reference Domain (work orders #001-#008),
--                canonical governed lookup table (ADR-001 / ADR-007 / ADR-008).
-- Dependencies:  Extension citext (0001).
-- Migration:     0008_foundation_reference_tables.sql
-- Rationale:     Audit event classes are governed, evolving business vocabulary:
--                translated, reordered, deprecated and governed over time. New
--                classes are data inserts, never schema changes. The audit
--                milestone records every event against one of these classes.
-- Columns:
--   code           Stable machine reference (snake_case).
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE audit_event_types (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint        NOT NULL,
    version_number  integer     NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT audit_event_types_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT audit_event_types_code_unique
        UNIQUE (code),
    CONSTRAINT audit_event_types_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE audit_event_types IS
    'Governed registry of audit event classes (created, updated, merged, ...).';
COMMENT ON COLUMN audit_event_types.code IS
    'Stable machine reference (snake_case), e.g. created, status_changed, merged.';
COMMENT ON COLUMN audit_event_types.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';
