-- =============================================================================
-- MIGRATION 0012 - core_entity_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 14 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\23_companies.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: companies
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of companies (manufacturers, distributors,
--                retailers) that own brands and produce or supply products.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003). Foreign keys
--                are applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Companies are governed, provenance-tracked business entities,
--                not lookup vocabulary: they carry source attribution
--                (source_id), confidence, verification/approval/deprecation
--                state, actor columns and a version counter (ADR-005 note: actor
--                columns apply to governed entities, not lookup tables).
--                Translations (Arabic/English) live in company_translations.
-- Columns:
--   internal_code   Stable internal machine reference (unique, citext).
--   confidence_level  Numeric fact confidence in [0,1]; confidence_band is
--                     derived from this and never stored (ADR-007).
--   created_by/approved_by  Actor UUIDs; reference the future auth/identity
--                     service (no users table in this mission).
-- =============================================================================
CREATE TABLE companies (
    id               uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    internal_code    citext        NOT NULL,
    name             text          NOT NULL,
    description      text          NULL,
    status_id        bigint        NOT NULL,
    source_id        uuid          NULL,
    confidence_level numeric       NOT NULL DEFAULT 0.5,
    verified_at      timestamptz   NULL,
    approved_at      timestamptz   NULL,
    deprecated_at    timestamptz   NULL,
    version_number   integer       NOT NULL DEFAULT 1,
    created_by       uuid          NULL,
    approved_by      uuid          NULL,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),
    deleted_at       timestamptz   NULL,

    CONSTRAINT companies_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT companies_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT companies_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE companies IS
    'Canonical registry of companies (manufacturers, distributors, retailers).';
COMMENT ON COLUMN companies.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN companies.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN companies.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN companies.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN companies.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\24_company_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: company_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of companies. Arabic and English are
--                supported from day one; additional languages are data inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables companies (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in companies; all localized
--                text lives here, keyed by (company_id, language_id). Quality is
--                governed per row by translation_status; display_name is the
--                user-facing label and search_name a normalized search variant.
-- Columns:
--   company_id       Owner entity (FK companies).
--   language_id      Language of this row (FK languages).
--   name             Translated canonical name.
--   display_name     User-facing label.
--   search_name      Normalized variant for search indexing (nullable).
-- =============================================================================
CREATE TABLE company_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id         uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT company_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT company_translations_company_language_unique
        UNIQUE (company_id, language_id)
);

COMMENT ON TABLE company_translations IS
    'Per-language translations of companies (unique per company and language).';
COMMENT ON COLUMN company_translations.name IS
    'Translated canonical name of the company.';
COMMENT ON COLUMN company_translations.display_name IS
    'User-facing label for the company in this language.';
COMMENT ON COLUMN company_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN company_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\25_brands.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: brands
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of brands. A brand belongs to exactly one
--                company; products attach to brands (generic/unbranded products
--                may attach to none).
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003), companies
--                (0012). Foreign keys are applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Brands are governed, provenance-tracked business entities with
--                the same canonical governance column set as companies. The
--                company relationship is applied as a foreign key in 0013.
--                Translations (Arabic/English) live in brand_translations.
-- Columns:
--   company_id      Owning company (FK companies, NOT NULL).
--   internal_code   Stable internal machine reference (unique, citext).
-- =============================================================================
CREATE TABLE brands (
    id               uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id       uuid          NOT NULL,
    internal_code    citext        NOT NULL,
    name             text          NOT NULL,
    description      text          NULL,
    status_id        bigint        NOT NULL,
    source_id        uuid          NULL,
    confidence_level numeric       NOT NULL DEFAULT 0.5,
    verified_at      timestamptz   NULL,
    approved_at      timestamptz   NULL,
    deprecated_at    timestamptz   NULL,
    version_number   integer       NOT NULL DEFAULT 1,
    created_by       uuid          NULL,
    approved_by      uuid          NULL,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),
    deleted_at       timestamptz   NULL,

    CONSTRAINT brands_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT brands_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT brands_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE brands IS
    'Canonical registry of brands, each owned by exactly one company.';
COMMENT ON COLUMN brands.company_id IS
    'Owning company (foreign key to companies).';
COMMENT ON COLUMN brands.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN brands.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN brands.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN brands.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN brands.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\26_brand_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: brand_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of brands. Arabic and English are
--                supported from day one; additional languages are data inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables brands (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in brands; all localized
--                text lives here, keyed by (brand_id, language_id). Quality is
--                governed per row by translation_status; display_name is the
--                user-facing label and search_name a normalized search variant.
-- Columns:
--   brand_id         Owner entity (FK brands).
--   language_id      Language of this row (FK languages).
-- =============================================================================
CREATE TABLE brand_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    brand_id           uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT brand_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT brand_translations_brand_language_unique
        UNIQUE (brand_id, language_id)
);

COMMENT ON TABLE brand_translations IS
    'Per-language translations of brands (unique per brand and language).';
COMMENT ON COLUMN brand_translations.name IS
    'Translated canonical name of the brand.';
COMMENT ON COLUMN brand_translations.display_name IS
    'User-facing label for the brand in this language.';
COMMENT ON COLUMN brand_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN brand_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\27_products.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: products
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of products. A product may belong to one
--                brand (NULL = generic/unbranded) and may be classified into one
--                product_categories taxonomy node.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003), brands (0012),
--                product_categories (0008). FKs applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Products are the central governed, provenance-tracked entity.
--                Nutrition facts, ingredient membership, images, and health
--                flags are separate later-milestone tables; this mission builds
--                only the canonical product core. Brand and category links are
--                applied as foreign keys in 0013.
-- Columns:
--   brand_id           Owning brand (FK brands); NULL for unbranded products.
--   product_category_id  Classification node (FK product_categories); NULL when
--                     not yet classified.
--   internal_code      Stable internal machine reference (unique, citext).
-- =============================================================================
CREATE TABLE products (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    brand_id           uuid          NULL,
    product_category_id uuid         NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    version_number     integer       NOT NULL DEFAULT 1,
    created_by         uuid          NULL,
    approved_by        uuid          NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now(),
    deleted_at         timestamptz   NULL,

    CONSTRAINT products_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT products_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT products_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE products IS
    'Canonical registry of products (governed, provenance-tracked core entity).';
COMMENT ON COLUMN products.brand_id IS
    'Owning brand (foreign key to brands); NULL for generic/unbranded products.';
COMMENT ON COLUMN products.product_category_id IS
    'Classification node (foreign key to product_categories); NULL when unclassified.';
COMMENT ON COLUMN products.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN products.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN products.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN products.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN products.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\28_product_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of products. Arabic and English are
--                supported from day one; additional languages are data inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables products (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in products; all localized
--                text lives here, keyed by (product_id, language_id). Quality is
--                governed per row by translation_status; display_name is the
--                user-facing label and search_name a normalized search variant.
-- Columns:
--   product_id       Owner entity (FK products).
--   language_id      Language of this row (FK languages).
-- =============================================================================
CREATE TABLE product_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id         uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT product_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_translations_product_language_unique
        UNIQUE (product_id, language_id)
);

COMMENT ON TABLE product_translations IS
    'Per-language translations of products (unique per product and language).';
COMMENT ON COLUMN product_translations.name IS
    'Translated canonical name of the product.';
COMMENT ON COLUMN product_translations.display_name IS
    'User-facing label for the product in this language.';
COMMENT ON COLUMN product_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN product_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\29_ingredients.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredients
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of ingredients (single canonical record per
--                ingredient). Ingredient hierarchies and aliases are separate
--                later-milestone structures; this mission builds the core.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003). Foreign keys
--                are applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Ingredients are governed, provenance-tracked business entities
--                with the canonical governance column set. Translations
--                (Arabic/English) live in ingredient_translations. Category
--                membership (ingredient_categories) is a relationship applied in
--                a later milestone, not duplicated here.
-- Columns:
--   internal_code   Stable internal machine reference (unique, citext).
-- =============================================================================
CREATE TABLE ingredients (
    id               uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    internal_code    citext        NOT NULL,
    name             text          NOT NULL,
    description      text          NULL,
    status_id        bigint        NOT NULL,
    source_id        uuid          NULL,
    confidence_level numeric       NOT NULL DEFAULT 0.5,
    verified_at      timestamptz   NULL,
    approved_at      timestamptz   NULL,
    deprecated_at    timestamptz   NULL,
    version_number   integer       NOT NULL DEFAULT 1,
    created_by       uuid          NULL,
    approved_by      uuid          NULL,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),
    deleted_at       timestamptz   NULL,

    CONSTRAINT ingredients_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredients_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredients_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE ingredients IS
    'Canonical registry of ingredients (governed, provenance-tracked core entity).';
COMMENT ON COLUMN ingredients.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN ingredients.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN ingredients.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN ingredients.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN ingredients.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\30_ingredient_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of ingredients. Arabic and English are
--                supported from day one; additional languages are data inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables ingredients (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in ingredients; all localized
--                text lives here, keyed by (ingredient_id, language_id). Quality
--                is governed per row by translation_status; display_name is the
--                user-facing label and search_name a normalized search variant.
-- Columns:
--   ingredient_id   Owner entity (FK ingredients).
--   language_id     Language of this row (FK languages).
-- =============================================================================
CREATE TABLE ingredient_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ingredient_id      uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT ingredient_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_translations_ingredient_language_unique
        UNIQUE (ingredient_id, language_id)
);

COMMENT ON TABLE ingredient_translations IS
    'Per-language translations of ingredients (unique per ingredient and language).';
COMMENT ON COLUMN ingredient_translations.name IS
    'Translated canonical name of the ingredient.';
COMMENT ON COLUMN ingredient_translations.display_name IS
    'User-facing label for the ingredient in this language.';
COMMENT ON COLUMN ingredient_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN ingredient_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\31_allergens.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: allergens
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of specific allergens (e.g. almond,
--                wheat_gluten). Each allergen may be classified into one
--                allergen_types class (mission 02); a NULL type means the class
--                is not yet assigned.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003), allergen_types
--                (0008). Foreign keys are applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Allergens are governed, provenance-tracked business entities.
--                The class is a foreign key to the governed allergen_types
--                registry (ADR-001: business knowledge lives in data). Product
--                and ingredient allergen assignments are later-milestone
--                relationships, not duplicated here.
-- Columns:
--   allergen_type_id  Classification class (FK allergen_types); NULL when not
--                     yet classified.
--   internal_code     Stable internal machine reference (unique, citext).
-- =============================================================================
CREATE TABLE allergens (
    id               uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    allergen_type_id uuid          NULL,
    internal_code    citext        NOT NULL,
    name             text          NOT NULL,
    description      text          NULL,
    status_id        bigint        NOT NULL,
    source_id        uuid          NULL,
    confidence_level numeric       NOT NULL DEFAULT 0.5,
    verified_at      timestamptz   NULL,
    approved_at      timestamptz   NULL,
    deprecated_at    timestamptz   NULL,
    version_number   integer       NOT NULL DEFAULT 1,
    created_by       uuid          NULL,
    approved_by      uuid          NULL,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),
    deleted_at       timestamptz   NULL,

    CONSTRAINT allergens_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT allergens_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT allergens_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE allergens IS
    'Canonical registry of specific allergens (governed, provenance-tracked entity).';
COMMENT ON COLUMN allergens.allergen_type_id IS
    'Allergen class (foreign key to allergen_types); NULL when not yet classified.';
COMMENT ON COLUMN allergens.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN allergens.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN allergens.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN allergens.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN allergens.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\32_allergen_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: allergen_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of allergens. Arabic and English are
--                supported from day one; additional languages are data inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables allergens (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in allergens; all localized
--                text lives here, keyed by (allergen_id, language_id). Quality is
--                governed per row by translation_status; display_name is the
--                user-facing label and search_name a normalized search variant.
-- Columns:
--   allergen_id     Owner entity (FK allergens).
--   language_id     Language of this row (FK languages).
-- =============================================================================
CREATE TABLE allergen_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    allergen_id        uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT allergen_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT allergen_translations_allergen_language_unique
        UNIQUE (allergen_id, language_id)
);

COMMENT ON TABLE allergen_translations IS
    'Per-language translations of allergens (unique per allergen and language).';
COMMENT ON COLUMN allergen_translations.name IS
    'Translated canonical name of the allergen.';
COMMENT ON COLUMN allergen_translations.display_name IS
    'User-facing label for the allergen in this language.';
COMMENT ON COLUMN allergen_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN allergen_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\33_nutrition_type_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: nutrition_type_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of nutrition fact types. The base
--                registry (nutrition_types, mission 02) already exists as a
--                governed lookup table (ADR-008); this mission adds its
--                translation layer. Arabic and English supported from day one.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables nutrition_types (0008),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     nutrition_types is unchanged from Mission 02 (no redesign);
--                localized display text arrives here. Keyed by
--                (nutrition_type_id, language_id). Quality is governed per row
--                by translation_status.
-- Columns:
--   nutrition_type_id  Owner entity (FK nutrition_types).
--   language_id        Language of this row (FK languages).
-- =============================================================================
CREATE TABLE nutrition_type_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    nutrition_type_id  uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT nutrition_type_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT nutrition_type_translations_nutrition_type_language_unique
        UNIQUE (nutrition_type_id, language_id)
);

COMMENT ON TABLE nutrition_type_translations IS
    'Per-language translations of nutrition fact types (unique per type and language).';
COMMENT ON COLUMN nutrition_type_translations.name IS
    'Translated canonical name of the nutrition fact type.';
COMMENT ON COLUMN nutrition_type_translations.display_name IS
    'User-facing label for the nutrition fact type in this language.';
COMMENT ON COLUMN nutrition_type_translations.search_name IS
    'Normalized search variant; NULL when not needed.';
COMMENT ON COLUMN nutrition_type_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\34_product_category_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_category_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of product categories. The base
--                taxonomy (product_categories, mission 02) already exists as a
--                governed lookup table (ADR-008); this mission adds its
--                translation layer. Arabic and English supported from day one.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables product_categories
--                (0008), languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     product_categories is unchanged from Mission 02 (no redesign);
--                localized display text arrives here. Keyed by
--                (product_category_id, language_id). Quality is governed per row
--                by translation_status.
-- Columns:
--   product_category_id  Owner entity (FK product_categories).
--   language_id          Language of this row (FK languages).
-- =============================================================================
CREATE TABLE product_category_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_category_id uuid               NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT product_category_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_category_translations_category_language_unique
        UNIQUE (product_category_id, language_id)
);

COMMENT ON TABLE product_category_translations IS
    'Per-language translations of product categories (unique per category and language).';
COMMENT ON COLUMN product_category_translations.name IS
    'Translated canonical name of the product category.';
COMMENT ON COLUMN product_category_translations.display_name IS
    'User-facing label for the product category in this language.';
COMMENT ON COLUMN product_category_translations.search_name IS
    'Normalized search variant; NULL when not needed.';
COMMENT ON COLUMN product_category_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\35_health_flags.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: health_flags
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of concrete health/risk flags and claims
--                (e.g. gluten_free_claim, recall_2024_001). Each flag may be
--                classified into one health_flag_types class (mission 02); a
--                NULL type means the class is not yet assigned.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                primary business entity per the approved architecture.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003), data_sources (0003), health_flag_types
--                (0003). Foreign keys are applied in 0013 (03-constraints).
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     Health flags are governed, provenance-tracked business entities.
--                The class is a foreign key to the governed health_flag_types
--                registry (ADR-001). Product/ingredient flag assignments are
--                later-milestone relationships, not duplicated here.
-- Columns:
--   health_flag_type_id  Classification class (FK health_flag_types); NULL when
--                     not yet classified.
--   internal_code     Stable internal machine reference (unique, citext).
-- =============================================================================
CREATE TABLE health_flags (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    health_flag_type_id uuid         NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    version_number     integer       NOT NULL DEFAULT 1,
    created_by         uuid          NULL,
    approved_by        uuid          NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now(),
    deleted_at         timestamptz   NULL,

    CONSTRAINT health_flags_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT health_flags_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT health_flags_internal_code_unique
        UNIQUE (internal_code)
);

COMMENT ON TABLE health_flags IS
    'Canonical registry of concrete health/risk flags and claims.';
COMMENT ON COLUMN health_flags.health_flag_type_id IS
    'Health/risk flag class (foreign key to health_flag_types); NULL when not yet classified.';
COMMENT ON COLUMN health_flags.internal_code IS
    'Stable internal machine reference (unique, citext).';
COMMENT ON COLUMN health_flags.confidence_level IS
    'Numeric fact confidence in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN health_flags.created_by IS
    'UUID of the actor that created the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN health_flags.approved_by IS
    'UUID of the actor that approved the row; FK to the future auth service (none yet).';
COMMENT ON COLUMN health_flags.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\36_health_flag_translations.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: health_flag_translations
-- -----------------------------------------------------------------------------
-- Purpose:       Per-language translations of health flags. Arabic and English
--                are supported from day one; additional languages are data
--                inserts.
-- Work orders:   Mission 03: Canonical Core Entities (work orders #001-#008),
--                dedicated translation table per translatable entity.
-- Dependencies:  Enum translation_status (0002). Tables health_flags (0012),
--                languages (0003). Foreign keys applied in 0013.
-- Migration:     0012_core_entity_tables.sql
-- Rationale:     No language-specific columns exist in health_flags; all
--                localized text lives here, keyed by (health_flag_id,
--                language_id). Quality is governed per row by
--                translation_status; display_name is the user-facing label and
--                search_name a normalized search variant.
-- Columns:
--   health_flag_id  Owner entity (FK health_flags).
--   language_id     Language of this row (FK languages).
-- =============================================================================
CREATE TABLE health_flag_translations (
    id                 uuid                NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    health_flag_id     uuid                NOT NULL,
    language_id        uuid                NOT NULL,
    name               text                NOT NULL,
    short_name         text                NULL,
    display_name       text                NOT NULL,
    search_name        text                NULL,
    description        text                NULL,
    translation_status translation_status  NOT NULL DEFAULT 'draft',
    version_number     integer             NOT NULL DEFAULT 1,
    created_at         timestamptz         NOT NULL DEFAULT now(),
    updated_at         timestamptz         NOT NULL DEFAULT now(),
    deleted_at         timestamptz         NULL,

    CONSTRAINT health_flag_translations_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT health_flag_translations_health_flag_language_unique
        UNIQUE (health_flag_id, language_id)
);

COMMENT ON TABLE health_flag_translations IS
    'Per-language translations of health flags (unique per flag and language).';
COMMENT ON COLUMN health_flag_translations.name IS
    'Translated canonical name of the health flag.';
COMMENT ON COLUMN health_flag_translations.display_name IS
    'User-facing label for the health flag in this language.';
COMMENT ON COLUMN health_flag_translations.search_name IS
    'Normalized search variant (e.g. transliteration); NULL when not needed.';
COMMENT ON COLUMN health_flag_translations.translation_status IS
    'Governed quality lifecycle of this translation row.';
