-- =============================================================================
-- MIGRATION 0016 - relationship_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 8 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\37_product_ingredients.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_ingredients
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between a product and an ingredient it contains,
--                including an optional declared amount. The authoritative
--                ingredient list of a product is the set of ACTIVE rows here.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), product membership relationship.
-- Dependencies:  Tables products, ingredients (0012), relationship_types,
--                data_sources, evidence_types, units, lifecycle_statuses
--                (0003/0008). FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     A product may contain an ingredient via multiple relationship
--                types (contains_ingredient, may_contain_ingredient, ...). The
--                composite UNIQUE (product, ingredient, relationship type)
--                prevents duplicate assertions while leaving room for distinct
--                types. amount_value/unit_id are optional: many labels list
--                ingredients without declared quantities. Provenance and
--                confidence are carried per relationship (source_id,
--                evidence_type_id, confidence_level).
-- Columns:
--   product_id          Owning product (FK products).
--   ingredient_id       Contained ingredient (FK ingredients).
--   relationship_type_id  Type of membership (FK relationship_types).
--   amount_value        Optional declared amount; NULL when not declared.
--   unit_id             Unit of amount_value (FK units); NULL when amount NULL.
-- =============================================================================
CREATE TABLE product_ingredients (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    ingredient_id        uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    amount_value         numeric       NULL,
    unit_id              uuid          NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_ingredients_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_ingredients_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_ingredients_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_ingredients_amount_nonnegative_check
        CHECK (amount_value IS NULL OR amount_value >= 0),
    CONSTRAINT product_ingredients_amount_unit_pairing_check
        CHECK ((amount_value IS NULL AND unit_id IS NULL) OR (amount_value IS NOT NULL)),
    CONSTRAINT product_ingredients_subject_unique
        UNIQUE (product_id, ingredient_id, relationship_type_id)
);

COMMENT ON TABLE product_ingredients IS
    'Product-to-ingredient membership relationship with optional declared amount.';
COMMENT ON COLUMN product_ingredients.amount_value IS
    'Optional declared amount of the ingredient; NULL when the label lists no quantity.';
COMMENT ON COLUMN product_ingredients.unit_id IS
    'Unit of amount_value (foreign key to units); NULL when amount is NULL.';
COMMENT ON COLUMN product_ingredients.relationship_type_id IS
    'Membership kind (contains_ingredient, may_contain_ingredient, ...).';
COMMENT ON COLUMN product_ingredients.effective_from IS
    'Start of validity for this relationship; NULL = from creation.';
COMMENT ON COLUMN product_ingredients.effective_to IS
    'End of validity for this relationship; NULL = currently effective.';
COMMENT ON COLUMN product_ingredients.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\38_product_allergens.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_allergens
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between a product and an allergen it contains or
--                may contain. The relationship_type distinguishes declared
--                "contains" from risk-based "may contain" assertions.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), product membership relationship.
-- Dependencies:  Tables products, allergens (0012), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     Allergen exposure is a risk fact: the same product can carry a
--                confirmed allergen (contains_allergen) and a precautionary
--                allergen (may_contain_allergen). The composite UNIQUE
--                (product, allergen, relationship type) allows both while
--                rejecting duplicate assertions of the same type. Provenance
--                (source_id, evidence_type_id, confidence_level) is stored per
--                assertion so risk weighting can use it.
-- Columns:
--   product_id          Product carrying the allergen (FK products).
--   allergen_id         Allergen asserted for the product (FK allergens).
--   relationship_type_id  Contains vs. may-contain kind (FK relationship_types).
-- =============================================================================
CREATE TABLE product_allergens (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    allergen_id          uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_allergens_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_allergens_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_allergens_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_allergens_subject_unique
        UNIQUE (product_id, allergen_id, relationship_type_id)
);

COMMENT ON TABLE product_allergens IS
    'Product-to-allergen exposure relationship (declared and precautionary).';
COMMENT ON COLUMN product_allergens.relationship_type_id IS
    'Assertion kind: contains_allergen vs. may_contain_allergen (relationship_types).';
COMMENT ON COLUMN product_allergens.effective_from IS
    'Start of validity for this assertion; NULL = from creation.';
COMMENT ON COLUMN product_allergens.effective_to IS
    'End of validity for this assertion; NULL = currently effective.';
COMMENT ON COLUMN product_allergens.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\39_product_nutrition_values.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_nutrition_values
-- -----------------------------------------------------------------------------
-- Purpose:       Nutrition fact value for a product: a numeric amount of a
--                nutrition_types fact in a unit of measure, provenance-tracked
--                like every other relationship. One row per (product, fact
--                type, relationship type).
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), product nutrition-fact relationship.
-- Dependencies:  Tables products (0012), nutrition_types, units,
--                relationship_types, data_sources, evidence_types,
--                lifecycle_statuses (0003/0008). FKs applied in 0017.
-- Migration:     0016_relationship_tables.sql
-- Rationale:     Nutrition facts are governed, evidence-backed assertions: the
--                fact type and its unit are vocabulary rows, the value is
--                numeric, and provenance/confidence are recorded per fact. The
--                UNIQUE (product, nutrition_type, relationship type) prevents a
--                duplicate fact of the same kind. The basis of the value
--                (per-100g, per-serving, ...) is not modeled here; see Mission
--                04 report open questions.
-- Columns:
--   product_id          Product the fact belongs to (FK products).
--   nutrition_type_id   Fact type (energy, protein, sodium, ...) (FK nutrition_types).
--   amount_value        Numeric amount of the fact.
--   unit_id             Unit of amount_value (FK units).
--   relationship_type_id  Fact kind (provides_nutrition, ...) (FK relationship_types).
-- =============================================================================
CREATE TABLE product_nutrition_values (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    nutrition_type_id    uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    amount_value         numeric       NOT NULL,
    unit_id              uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_nutrition_values_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_nutrition_values_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_nutrition_values_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_nutrition_values_amount_nonnegative_check
        CHECK (amount_value >= 0),
    CONSTRAINT product_nutrition_values_fact_unique
        UNIQUE (product_id, nutrition_type_id, relationship_type_id)
);

COMMENT ON TABLE product_nutrition_values IS
    'Provenance-tracked nutrition fact values per product.';
COMMENT ON COLUMN product_nutrition_values.amount_value IS
    'Numeric amount of the nutrition fact (non-negative).';
COMMENT ON COLUMN product_nutrition_values.unit_id IS
    'Unit of amount_value (foreign key to units).';
COMMENT ON COLUMN product_nutrition_values.relationship_type_id IS
    'Fact kind (provides_nutrition, ...); reserved for future fact sub-kinds.';
COMMENT ON COLUMN product_nutrition_values.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\40_product_health_flags.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_health_flags
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between a product and a health_flag it carries
--                (claim, warning, risk). The relationship_type distinguishes
--                asserted claims from machine-derived warnings when needed.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), product membership relationship.
-- Dependencies:  Tables products, health_flags (0012), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     A product can carry several flags; a flag can apply to many
--                products. The composite UNIQUE (product, flag, relationship
--                type) prevents duplicate assertions. Flags are governed rows in
--                health_flags; this table stores only the link and its
--                provenance, never flag text (no duplication, ADR-007).
-- Columns:
--   product_id          Product the flag applies to (FK products).
--   health_flag_id      Applied flag (FK health_flags).
--   relationship_type_id  Kind of assertion (FK relationship_types).
-- =============================================================================
CREATE TABLE product_health_flags (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    health_flag_id       uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_health_flags_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_health_flags_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_health_flags_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_health_flags_subject_unique
        UNIQUE (product_id, health_flag_id, relationship_type_id)
);

COMMENT ON TABLE product_health_flags IS
    'Product-to-health-flag relationship (claims, warnings, risks).';
COMMENT ON COLUMN product_health_flags.relationship_type_id IS
    'Kind of flag assertion (has_health_flag, warns_about, ...).';
COMMENT ON COLUMN product_health_flags.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\41_ingredient_allergens.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_allergens
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between an ingredient and an allergen class it
--                contains or may contain. The canonical allergen registry
--                (allergens) classifies specific allergens by allergen_type;
--                this table links concrete ingredients to concrete allergens.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), ingredient membership relationship.
-- Dependencies:  Tables ingredients, allergens (0012), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     An ingredient may carry an allergen (wheat contains gluten) and
--                the same pair may be asserted with distinct relationship types
--                (contains vs. may-contain). UNIQUE (ingredient, allergen,
--                relationship type) rejects duplicate assertions. Ingredient
--                names and allergen data are never duplicated here — only the
--                link and its provenance.
-- Columns:
--   ingredient_id       Ingredient carrying the allergen (FK ingredients).
--   allergen_id         Allergen asserted for the ingredient (FK allergens).
--   relationship_type_id  Contains vs. may-contain kind (FK relationship_types).
-- =============================================================================
CREATE TABLE ingredient_allergens (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ingredient_id        uuid          NOT NULL,
    allergen_id          uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT ingredient_allergens_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_allergens_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredient_allergens_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT ingredient_allergens_subject_unique
        UNIQUE (ingredient_id, allergen_id, relationship_type_id)
);

COMMENT ON TABLE ingredient_allergens IS
    'Ingredient-to-allergen relationship (declared and precautionary).';
COMMENT ON COLUMN ingredient_allergens.relationship_type_id IS
    'Assertion kind: contains_allergen vs. may_contain_allergen (relationship_types).';
COMMENT ON COLUMN ingredient_allergens.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\42_ingredient_health_flags.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_health_flags
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between an ingredient and a health_flag (claim,
--                warning, risk) that applies to the ingredient itself, e.g. an
--                additive with a regulatory caution.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), ingredient membership relationship.
-- Dependencies:  Tables ingredients, health_flags (0012), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     Mirrors product_health_flags for the ingredient registry: a
--                flag applies to many ingredients and an ingredient can carry
--                several flags. The composite UNIQUE (ingredient, flag,
--                relationship type) rejects duplicate assertions. No flag text
--                is duplicated here (ADR-007).
-- Columns:
--   ingredient_id       Ingredient the flag applies to (FK ingredients).
--   health_flag_id      Applied flag (FK health_flags).
--   relationship_type_id  Kind of assertion (FK relationship_types).
-- =============================================================================
CREATE TABLE ingredient_health_flags (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ingredient_id        uuid          NOT NULL,
    health_flag_id       uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT ingredient_health_flags_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_health_flags_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredient_health_flags_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT ingredient_health_flags_subject_unique
        UNIQUE (ingredient_id, health_flag_id, relationship_type_id)
);

COMMENT ON TABLE ingredient_health_flags IS
    'Ingredient-to-health-flag relationship (claims, warnings, risks).';
COMMENT ON COLUMN ingredient_health_flags.relationship_type_id IS
    'Kind of flag assertion (has_health_flag, warns_about, ...).';
COMMENT ON COLUMN ingredient_health_flags.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\43_ingredient_aliases.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_aliases
-- -----------------------------------------------------------------------------
-- Purpose:       Alternate names for an ingredient (E-number, trade synonym,
--                regional spelling) used for matching and search. One
--                ingredient has many aliases; an alias belongs to one ingredient.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), ingredient naming relationship.
-- Dependencies:  Tables ingredients (0012), languages (0003), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0017 (03-constraints).
-- Migration:     0016_relationship_tables.sql
-- Rationale:     The canonical ingredient name lives in ingredients.name and its
--                localized forms in ingredient_translations; aliases are
--                additional accepted strings (e.g. "E621", "monosodium
--                glutamate", regional transliterations) that must not pollute
--                the canonical name. language_id scopes an alias to a language
--                when it is a transliteration; NULL means language-neutral.
--                UNIQUE (ingredient_id, alias) prevents duplicate aliases.
-- Columns:
--   ingredient_id       Owning ingredient (FK ingredients).
--   alias               Alternate accepted name for the ingredient.
--   language_id         Language of the alias; NULL = language-neutral (FK languages).
--   relationship_type_id  Alias kind (synonym, e_number, transliteration, ...).
-- =============================================================================
CREATE TABLE ingredient_aliases (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ingredient_id        uuid          NOT NULL,
    alias                text          NOT NULL,
    language_id          uuid          NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT ingredient_aliases_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_aliases_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredient_aliases_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT ingredient_aliases_alias_not_blank_check
        CHECK (alias <> ''),
    CONSTRAINT ingredient_aliases_ingredient_alias_unique
        UNIQUE (ingredient_id, alias)
);

COMMENT ON TABLE ingredient_aliases IS
    'Alternate accepted names for an ingredient, for matching and search.';
COMMENT ON COLUMN ingredient_aliases.alias IS
    'Alternate accepted name (e.g. E621, monosodium glutamate); never blank.';
COMMENT ON COLUMN ingredient_aliases.language_id IS
    'Language of a transliteration alias; NULL means language-neutral.';
COMMENT ON COLUMN ingredient_aliases.relationship_type_id IS
    'Alias kind: synonym, e_number, transliteration, ... (relationship_types).';
COMMENT ON COLUMN ingredient_aliases.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\44_entity_relationships.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: entity_relationships
-- -----------------------------------------------------------------------------
-- Purpose:       Knowledge-graph edges between any two canonical core entities
--                (companies, brands, products, ingredients, allergens,
--                health_flags). The relationship_types registry defines the
--                edge vocabulary (contains_ingredient, similar_to,
--                substitutable_for, ...), with inverse pairing, so new edge
--                kinds are governed data inserts, never schema changes.
-- Work orders:   Mission 04: Relationship & Junction Tables (work orders
--                #001-#008), knowledge-graph edge table.
-- Dependencies:  Tables relationship_types, data_sources, evidence_types,
--                lifecycle_statuses (0003/0008); core entities (0012). The
--                subject/object endpoint tables must exist. FKs applied in 0017.
-- Migration:     0016_relationship_tables.sql
-- Rationale:     A polymorphic edge table cannot carry a single foreign key to
--                several entity tables. Each endpoint is therefore a UUID plus
--                an entity-type discriminator; the endpoint TYPE is validated by
--                CHECK against the set of canonical core entities, and the
--                endpoint ID is validated at the application layer and by future
--                triggers (see Mission 04 report, assumptions). No information
--                is duplicated from the endpoint entities; only the edge and its
--                provenance are stored. A directed self-relationship between two
--                distinct rows of the same entity (e.g. ingredient A similar to
--                ingredient B) is allowed; a self-loop (A similar to A) is
--                rejected by CHECK. The UNIQUE constraint over
--                (subject, object, type) prevents duplicate edges.
-- Columns:
--   subject_entity_type  Entity kind of the edge subject (CHECK list).
--   subject_id           UUID of the subject entity (no FK: polymorphic).
--   object_entity_type   Entity kind of the edge object (CHECK list).
--   object_id            UUID of the object entity (no FK: polymorphic).
--   relationship_type_id  Edge type (FK relationship_types), governs semantics.
-- =============================================================================
CREATE TABLE entity_relationships (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    subject_entity_type  text          NOT NULL,
    subject_id           uuid          NOT NULL,
    object_entity_type   text          NOT NULL,
    object_id            uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT entity_relationships_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT entity_relationships_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT entity_relationships_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT entity_relationships_subject_entity_type_check
        CHECK (subject_entity_type IN ('companies', 'brands', 'products', 'ingredients', 'allergens', 'health_flags')),
    CONSTRAINT entity_relationships_object_entity_type_check
        CHECK (object_entity_type IN ('companies', 'brands', 'products', 'ingredients', 'allergens', 'health_flags')),
    CONSTRAINT entity_relationships_no_self_loop_check
        CHECK (subject_entity_type <> object_entity_type OR subject_id <> object_id),
    CONSTRAINT entity_relationships_edge_unique
        UNIQUE (subject_entity_type, subject_id, relationship_type_id, object_entity_type, object_id)
);

COMMENT ON TABLE entity_relationships IS
    'Polymorphic knowledge-graph edges between canonical core entities.';
COMMENT ON COLUMN entity_relationships.subject_entity_type IS
    'Entity kind of the edge subject; restricted to the canonical core entities.';
COMMENT ON COLUMN entity_relationships.subject_id IS
    'UUID of the subject entity; integrity enforced at the application/trigger layer (polymorphic endpoint).';
COMMENT ON COLUMN entity_relationships.object_entity_type IS
    'Entity kind of the edge object; restricted to the canonical core entities.';
COMMENT ON COLUMN entity_relationships.object_id IS
    'UUID of the object entity; integrity enforced at the application/trigger layer (polymorphic endpoint).';
COMMENT ON COLUMN entity_relationships.relationship_type_id IS
    'Edge type (foreign key to relationship_types); the governed edge vocabulary.';
COMMENT ON COLUMN entity_relationships.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';
