-- =============================================================================
-- MIGRATION 0020 - history_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 9 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\45_companies_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: companies_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity companies.
--                One row per published version of a company, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity companies (0012).
--                Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance). This keeps the
--                snapshot purely business/lifecycle state with no field
--                duplicated between snapshot and header.
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   original_entity_id  Canonical entity this version belongs to (FK companies).
--   version_number      Monotonic version of the canonical entity at this row.
--   previous_version_id Self-reference to the immediately prior version row.
--   change_type         Nature of the change (existing update_type ENUM).
--   snapshot_hash       SHA-256 of the snapshot columns (application-computed).
--   checksum            Checksum of the full history row for tamper evidence.
-- =============================================================================
CREATE TABLE companies_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT companies_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT companies_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT companies_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT companies_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE companies_history IS
    'Immutable version-history of companies (INSERT-only; one row per version).';
COMMENT ON COLUMN companies_history.original_entity_id IS
    'Canonical company this version belongs to (foreign key to companies, applied in 0022).';
COMMENT ON COLUMN companies_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN companies_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN companies_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN companies_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN companies_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\46_brands_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: brands_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity brands.
--                One row per published version of a brand, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity brands (0012).
--                Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   original_entity_id  Canonical entity this version belongs to (FK brands).
--   company_id          Owning company at this version (FK companies).
--   version_number      Monotonic version of the canonical entity at this row.
--   previous_version_id Self-reference to the immediately prior version row.
-- =============================================================================
CREATE TABLE brands_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    company_id         uuid          NOT NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT brands_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT brands_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT brands_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT brands_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE brands_history IS
    'Immutable version-history of brands (INSERT-only; one row per version).';
COMMENT ON COLUMN brands_history.original_entity_id IS
    'Canonical brand this version belongs to (foreign key to brands, applied in 0022).';
COMMENT ON COLUMN brands_history.company_id IS
    'Owning company at this version (foreign key to companies, applied in 0022).';
COMMENT ON COLUMN brands_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN brands_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN brands_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN brands_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN brands_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\47_products_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: products_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity products.
--                One row per published version of a product, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity products (0012).
--                Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   original_entity_id  Canonical entity this version belongs to (FK products).
--   brand_id            Owning brand at this version (FK brands); NULL unbranded.
--   product_category_id Classification node at this version (FK product_categories).
-- =============================================================================
CREATE TABLE products_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    brand_id           uuid          NULL,
    product_category_id uuid         NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT products_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT products_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT products_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT products_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE products_history IS
    'Immutable version-history of products (INSERT-only; one row per version).';
COMMENT ON COLUMN products_history.original_entity_id IS
    'Canonical product this version belongs to (foreign key to products, applied in 0022).';
COMMENT ON COLUMN products_history.brand_id IS
    'Owning brand at this version (foreign key to brands, applied in 0022); NULL for unbranded products.';
COMMENT ON COLUMN products_history.product_category_id IS
    'Classification node at this version (foreign key to product_categories, applied in 0022).';
COMMENT ON COLUMN products_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN products_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN products_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN products_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN products_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\48_ingredients_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredients_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity ingredients.
--                One row per published version of an ingredient, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity ingredients
--                (0012). Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- =============================================================================
CREATE TABLE ingredients_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT ingredients_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredients_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredients_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ingredients_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE ingredients_history IS
    'Immutable version-history of ingredients (INSERT-only; one row per version).';
COMMENT ON COLUMN ingredients_history.original_entity_id IS
    'Canonical ingredient this version belongs to (foreign key to ingredients, applied in 0022).';
COMMENT ON COLUMN ingredients_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN ingredients_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN ingredients_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN ingredients_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN ingredients_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\49_allergens_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: allergens_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity allergens.
--                One row per published version of an allergen, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity allergens (0012).
--                Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   allergen_type_id    Allergen class at this version (FK allergen_types).
-- =============================================================================
CREATE TABLE allergens_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    allergen_type_id   uuid          NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT allergens_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT allergens_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT allergens_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT allergens_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE allergens_history IS
    'Immutable version-history of allergens (INSERT-only; one row per version).';
COMMENT ON COLUMN allergens_history.original_entity_id IS
    'Canonical allergen this version belongs to (foreign key to allergens, applied in 0022).';
COMMENT ON COLUMN allergens_history.allergen_type_id IS
    'Allergen class at this version (foreign key to allergen_types, applied in 0022).';
COMMENT ON COLUMN allergens_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN allergens_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN allergens_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN allergens_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN allergens_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\50_health_flags_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: health_flags_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the canonical entity health_flags.
--                One row per published version of a health flag, capturing the
--                complete governed snapshot plus versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical entity health_flags
--                (0012). Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot excludes id (mapped to original_entity_id),
--                version_number (mapped to this table's version_number),
--                created_by/approved_by (mapped to changed_by/approved_by),
--                source_id and confidence_level (carried by the history header),
--                and created_at/updated_at (the row's own created_at plus the
--                effective window cover temporal provenance).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   health_flag_type_id  Health/risk flag class at this version (FK health_flag_types).
-- =============================================================================
CREATE TABLE health_flags_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    health_flag_type_id uuid        NULL,
    internal_code      citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    status_id          bigint        NOT NULL,
    verified_at        timestamptz   NULL,
    approved_at        timestamptz   NULL,
    deprecated_at      timestamptz   NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT health_flags_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT health_flags_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT health_flags_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT health_flags_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE health_flags_history IS
    'Immutable version-history of health_flags (INSERT-only; one row per version).';
COMMENT ON COLUMN health_flags_history.original_entity_id IS
    'Canonical health flag this version belongs to (foreign key to health_flags, applied in 0022).';
COMMENT ON COLUMN health_flags_history.health_flag_type_id IS
    'Health/risk flag class at this version (foreign key to health_flag_types, applied in 0022).';
COMMENT ON COLUMN health_flags_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN health_flags_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN health_flags_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN health_flags_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN health_flags_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\51_nutrition_types_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: nutrition_types_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the governed lookup entity
--                nutrition_types. One row per published version of a nutrition
--                type, capturing the complete snapshot plus versioning and audit
--                metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical lookup nutrition_types
--                (0008). Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot mirrors the governed lookup columns of the canonical
--                table (code/name/description/display_order/status_id/deleted_at);
--                it excludes id (mapped to original_entity_id) and
--                version_number (mapped to this table's version_number).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   code               Governed machine code at this version (not unique here:
--                      many versions share one entity code).
-- =============================================================================
CREATE TABLE nutrition_types_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    code               citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    display_order      integer       NOT NULL DEFAULT 0,
    status_id          bigint        NOT NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT nutrition_types_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT nutrition_types_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT nutrition_types_history_display_order_check
        CHECK (display_order >= 0),
    CONSTRAINT nutrition_types_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT nutrition_types_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE nutrition_types_history IS
    'Immutable version-history of nutrition_types (INSERT-only; one row per version).';
COMMENT ON COLUMN nutrition_types_history.original_entity_id IS
    'Canonical nutrition type this version belongs to (foreign key to nutrition_types, applied in 0022).';
COMMENT ON COLUMN nutrition_types_history.code IS
    'Governed machine code at this version (snake_case); not unique in history because several versions share one entity code.';
COMMENT ON COLUMN nutrition_types_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN nutrition_types_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN nutrition_types_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN nutrition_types_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN nutrition_types_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\52_product_categories_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_categories_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the governed taxonomy entity
--                product_categories. One row per published version of a product
--                category, capturing the complete snapshot plus versioning and
--                audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical lookup product_categories
--                (0008). Foreign keys are applied in 0022 (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot mirrors the governed lookup columns of the canonical
--                table (code/name/description/parent_id/display_order/status_id/
--                deleted_at); it excludes id (mapped to original_entity_id) and
--                version_number (mapped to this table's version_number).
--                Mission 05 lists a single "categories_history"; product and
--                ingredient categories are distinct governed tables, so each
--                receives its own history table (see Mission 05 report,
--                Assumptions 1).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   parent_id          Taxonomy parent at this version (FK product_categories);
--                      NULL for roots.
-- =============================================================================
CREATE TABLE product_categories_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    code               citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    parent_id          uuid          NULL,
    display_order      integer       NOT NULL DEFAULT 0,
    status_id          bigint        NOT NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT product_categories_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_categories_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_categories_history_display_order_check
        CHECK (display_order >= 0),
    CONSTRAINT product_categories_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_categories_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE product_categories_history IS
    'Immutable version-history of product_categories (INSERT-only; one row per version).';
COMMENT ON COLUMN product_categories_history.original_entity_id IS
    'Canonical product category this version belongs to (foreign key to product_categories, applied in 0022).';
COMMENT ON COLUMN product_categories_history.parent_id IS
    'Taxonomy parent at this version (self-reference to product_categories, applied in 0022); NULL for taxonomy roots.';
COMMENT ON COLUMN product_categories_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN product_categories_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN product_categories_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN product_categories_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN product_categories_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\53_ingredient_categories_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_categories_history
-- -----------------------------------------------------------------------------
-- Purpose:       Immutable version-history for the governed taxonomy entity
--                ingredient_categories. One row per published version of an
--                ingredient category, capturing the complete snapshot plus
--                versioning and audit metadata.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Extension citext (0001). Enums update_type / version_status
--                (0002). Lifecycle lifecycle_statuses (0003), data_sources
--                (0003), change_sets (0021). Canonical lookup
--                ingredient_categories (0008). Foreign keys are applied in 0022
--                (03-constraints).
-- Migration:     0020_history_tables.sql
-- Rationale:     History is immutable by design: rows are INSERT-only (enforced
--                by triggers in 0024) and are never updated or deleted. The
--                snapshot mirrors the governed lookup columns of the canonical
--                table (code/name/description/parent_id/display_order/status_id/
--                deleted_at); it excludes id (mapped to original_entity_id) and
--                version_number (mapped to this table's version_number).
--                Mission 05 lists a single "categories_history"; product and
--                ingredient categories are distinct governed tables, so each
--                receives its own history table (see Mission 05 report,
--                Assumptions 1).
-- Deviation:     The standard audit-trio layout (created_at/updated_at/deleted_at,
--                sql_conventions.md) is intentionally not followed: an immutable
--                row has no updated_at and is never soft-deleted. The entity's
--                deleted_at IS captured in the snapshot as business state.
-- Columns:
--   parent_id          Taxonomy parent at this version (FK ingredient_categories);
--                      NULL for roots.
-- =============================================================================
CREATE TABLE ingredient_categories_history (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    original_entity_id uuid          NOT NULL,
    version_number     integer       NOT NULL,
    previous_version_id uuid         NULL,
    change_set_id      uuid          NULL,
    change_type        update_type   NOT NULL,
    change_reason      text          NULL,
    changed_by         uuid          NULL,
    approved_by        uuid          NULL,
    source_id          uuid          NULL,
    confidence_level   numeric       NOT NULL DEFAULT 0.5,
    code               citext        NOT NULL,
    name               text          NOT NULL,
    description        text          NULL,
    parent_id          uuid          NULL,
    display_order      integer       NOT NULL DEFAULT 0,
    status_id          bigint        NOT NULL,
    deleted_at         timestamptz   NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    effective_from     timestamptz   NOT NULL DEFAULT now(),
    effective_to       timestamptz   NULL,
    superseded_at      timestamptz   NULL,
    snapshot_hash      text          NOT NULL,
    checksum           text          NOT NULL,
    version_status     version_status NOT NULL DEFAULT 'draft',

    CONSTRAINT ingredient_categories_history_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT ingredient_categories_history_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT ingredient_categories_history_display_order_check
        CHECK (display_order >= 0),
    CONSTRAINT ingredient_categories_history_effective_window_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ingredient_categories_history_entity_version_unique
        UNIQUE (original_entity_id, version_number)
);

COMMENT ON TABLE ingredient_categories_history IS
    'Immutable version-history of ingredient_categories (INSERT-only; one row per version).';
COMMENT ON COLUMN ingredient_categories_history.original_entity_id IS
    'Canonical ingredient category this version belongs to (foreign key to ingredient_categories, applied in 0022).';
COMMENT ON COLUMN ingredient_categories_history.parent_id IS
    'Taxonomy parent at this version (self-reference to ingredient_categories, applied in 0022); NULL for taxonomy roots.';
COMMENT ON COLUMN ingredient_categories_history.previous_version_id IS
    'Self-reference to the immediately prior version row; NULL for the first version.';
COMMENT ON COLUMN ingredient_categories_history.change_type IS
    'Nature of the change recorded by this version (existing update_type ENUM).';
COMMENT ON COLUMN ingredient_categories_history.snapshot_hash IS
    'SHA-256 of the snapshot columns (application-computed) to verify a stored version matches the original state.';
COMMENT ON COLUMN ingredient_categories_history.checksum IS
    'Checksum of the full history row for tamper evidence.';
COMMENT ON COLUMN ingredient_categories_history.version_status IS
    'Version lifecycle: draft -> pending_approval -> approved -> superseded (existing version_status ENUM).';
