-- =============================================================================
-- MIGRATION 0024 - history_triggers
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 3 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\06-functions\02_prevent_history_mutation.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Function: prevent_history_mutation()
-- -----------------------------------------------------------------------------
-- Purpose:       Shared trigger function that rejects UPDATE and DELETE on
--                immutable history tables. History is INSERT-only by design
--                (Mission 05), so any attempt to change or remove a recorded
--                version raises an exception.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  None (plpgsql is built in). Called by triggers in 07-triggers.
-- Migration:     0024_history_triggers.sql
-- Rationale:     Immutability is enforced by the database, not by application
--                discipline: a history row is a factual record of a governed
--                change and must never be altered. The mission's PASS criterion
--                "immutable strategy" is satisfied at the storage layer.
-- =============================================================================
CREATE OR REPLACE FUNCTION prevent_history_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'immutable history: % on % is not permitted (history rows are INSERT-only)',
        TG_OP,
        TG_TABLE_NAME;
END;
$$;

COMMENT ON FUNCTION prevent_history_mutation() IS
    'Raises an exception on UPDATE/DELETE of immutable history rows.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\05_history_immutability.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: History Table Immutability
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared prevent_history_mutation() function to every
--                Mission 05 history table. History rows are INSERT-only: UPDATE
--                and DELETE are rejected at the storage layer.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Function prevent_history_mutation() (06-functions, 0024).
--                Mission 05 history tables (0020).
-- Migration:     0024_history_triggers.sql
-- Rationale:     One trigger per history table keeps the rule explicit and
--                auditable, matching the repository's per-table trigger style.
-- =============================================================================
CREATE TRIGGER companies_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON companies_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER brands_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON brands_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER products_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON products_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER ingredients_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON ingredients_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER allergens_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON allergens_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER health_flags_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON health_flags_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER nutrition_types_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON nutrition_types_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER product_categories_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON product_categories_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER ingredient_categories_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON ingredient_categories_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\06_audit_tables_updated_at.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: Audit Tables updated_at
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared set_updated_at() function to every Mission 05
--                audit table carrying the audit lifecycle columns.
-- Work orders:   Mission 05: Version History & Audit Infrastructure (work orders
--                #001-#008).
-- Dependencies:  Function set_updated_at() (06-functions, 0006). Mission 05
--                audit tables (0021).
-- Migration:     0024_history_triggers.sql
-- Rationale:     Every table with updated_at must stamp it on UPDATE. Declaring
--                one trigger per table here keeps the rule explicit and auditable.
-- =============================================================================
CREATE TRIGGER audit_context_set_updated_at
    BEFORE UPDATE ON audit_context
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER change_sets_set_updated_at
    BEFORE UPDATE ON change_sets
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER audit_log_set_updated_at
    BEFORE UPDATE ON audit_log
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER audit_events_set_updated_at
    BEFORE UPDATE ON audit_events
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER entity_versions_set_updated_at
    BEFORE UPDATE ON entity_versions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER version_metadata_set_updated_at
    BEFORE UPDATE ON version_metadata
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
