-- =============================================================================
-- MIGRATION 0025 - media_and_barcode_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 3 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\60_verification_statuses.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: verification_statuses
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of barcode verification states. Verification
--                answers "can this barcode be trusted?" and is orthogonal to the
--                lifecycle status (ADR-008), which answers "should this barcode
--                participate in the published knowledge base?".
-- Work orders:   Mission 07: Canonical Media & Barcode Domain.
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003). Foreign keys applied in 0027
--                (03-constraints).
-- Migration:     0025_media_and_barcode_tables.sql
-- Rationale:     Verification is governed business vocabulary (ADR-001), modeled
--                as a lookup table so states are extensible by governance, never
--                by ALTER TYPE (ADR-007). It is deliberately NOT an ENUM and NOT
--                a lifecycle duplicate: a barcode carries both status_id
--                (lifecycle) and verification_status_id (verification).
-- Columns:
--   code           Stable machine reference (snake_case, e.g. unverified).
--   display_order  Governance display ordering for pickers.
-- =============================================================================
CREATE TABLE verification_statuses (
    id              uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code            citext       NOT NULL,
    name            text         NOT NULL,
    description     text         NULL,
    display_order   integer      NOT NULL DEFAULT 0,
    status_id       bigint       NOT NULL,
    version_number  integer      NOT NULL DEFAULT 1,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    deleted_at      timestamptz  NULL,

    CONSTRAINT verification_statuses_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT verification_statuses_display_order_check
        CHECK (display_order >= 0),
    CONSTRAINT verification_statuses_code_unique
        UNIQUE (code)
);

COMMENT ON TABLE verification_statuses IS
    'Governed registry of barcode verification states (trust, not lifecycle).';
COMMENT ON COLUMN verification_statuses.code IS
    'Stable machine reference (snake_case; e.g. unverified, verified).';
COMMENT ON COLUMN verification_statuses.status_id IS
    'Lifecycle of the vocabulary row itself (foreign key to lifecycle_statuses).';
COMMENT ON COLUMN verification_statuses.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\61_images.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: images
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of governed media records. An image is NOT a
--                stored file: storage_uri references the object store and the
--                record carries its classification (image_type_id), provenance
--                (source_id), optional language scope, content fingerprint
--                (content_hash), technical attributes and lifecycle state.
-- Work orders:   Mission 07: Canonical Media & Barcode Domain.
-- Dependencies:  Extension citext (0001). Enum set (0002). Tables image_types,
--                data_sources, languages, lifecycle_statuses (0003). Foreign
--                keys applied in 0027 (03-constraints).
-- Migration:     0025_media_and_barcode_tables.sql
-- Rationale:     Media are governed records, so they follow the canonical entity
--                layout: lifecycle via status_id (ADR-008), monotonic version
--                counter, actor columns (created_by/updated_by/reviewed_by/
--                approved_by; no auth service yet, ADR-005) and the audit trio.
--                content_hash is the content fingerprint used for deduplication;
--                it is named content_hash (not checksum) because the immutable
--                history header already reserves the name checksum for row
--                tamper-evidence (Mission 05 architecture). metadata carries
--                optional EXIF/OCR context as JSONB.
-- Columns:
--   image_type_id    Classification (FK image_types): primary, front, back, ...
--   source_id        Provenance of the media record (FK data_sources).
--   language_id      Language scope of the media, NULL = language-neutral.
--   storage_uri      Reference to the stored object (never the bytes).
--   content_hash     Content fingerprint (SHA-256) for deduplication (unique).
--   mime_type        Media type of the stored object (e.g. image/jpeg).
-- =============================================================================
CREATE TABLE images (
    id                 uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    image_type_id      uuid          NOT NULL,
    source_id          uuid          NULL,
    language_id        uuid          NULL,
    storage_uri        text          NOT NULL,
    content_hash       text          NOT NULL,
    mime_type          text          NOT NULL,
    width              integer       NULL,
    height             integer       NULL,
    file_size          bigint        NOT NULL DEFAULT 0,
    status_id          bigint        NOT NULL,
    metadata           jsonb         NOT NULL DEFAULT '{}'::jsonb,
    version_number     integer       NOT NULL DEFAULT 1,
    created_by         uuid          NULL,
    updated_by         uuid          NULL,
    reviewed_by        uuid          NULL,
    approved_by        uuid          NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now(),
    deleted_at         timestamptz   NULL,

    CONSTRAINT images_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT images_dimension_width_check
        CHECK (width IS NULL OR width > 0),
    CONSTRAINT images_dimension_height_check
        CHECK (height IS NULL OR height > 0),
    CONSTRAINT images_file_size_check
        CHECK (file_size >= 0),
    CONSTRAINT images_storage_uri_unique
        UNIQUE (storage_uri),
    CONSTRAINT images_content_hash_unique
        UNIQUE (content_hash)
);

COMMENT ON TABLE images IS
    'Canonical registry of governed media records (references, not file storage).';
COMMENT ON COLUMN images.image_type_id IS
    'Classification of the image (foreign key to image_types): primary, front, back, nutrition panel, ...';
COMMENT ON COLUMN images.source_id IS
    'Provenance of the media record (foreign key to data_sources).';
COMMENT ON COLUMN images.language_id IS
    'Language scope of the media (foreign key to languages); NULL = language-neutral.';
COMMENT ON COLUMN images.storage_uri IS
    'Reference to the stored object in the object store (unique; never the bytes themselves).';
COMMENT ON COLUMN images.content_hash IS
    'Content fingerprint (SHA-256) used for deduplication (unique); the history header column checksum is reserved for row tamper-evidence.';
COMMENT ON COLUMN images.mime_type IS
    'Media type of the stored object (e.g. image/jpeg).';
COMMENT ON COLUMN images.file_size IS
    'Size of the stored object in bytes.';
COMMENT ON COLUMN images.metadata IS
    'Optional JSONB metadata (EXIF/OCR/context); additive, never queried relationally.';
COMMENT ON COLUMN images.status_id IS
    'Lifecycle of the media record (foreign key to lifecycle_statuses; ADR-008).';
COMMENT ON COLUMN images.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\62_barcodes.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: barcodes
-- -----------------------------------------------------------------------------
-- Purpose:       Canonical registry of barcodes. A barcode is a globally unique
--                code (GTIN family or other symbology) with its symbology
--                (barcode_type_id), issuer and jurisdiction, provenance, and two
--                orthogonal statuses: lifecycle (status_id, ADR-008) and
--                verification (verification_status_id).
-- Work orders:   Mission 07: Canonical Media & Barcode Domain.
-- Dependencies:  Extension citext (0001). Enum set (0002). Tables barcode_types,
--                verification_statuses (0025), data_sources, countries,
--                lifecycle_statuses (0003). Foreign keys applied in 0027
--                (03-constraints).
-- Migration:     0025_media_and_barcode_tables.sql
-- Rationale:     The barcode value is the natural, globally unique key (UNIQUE
--                barcode). Lifecycle follows ADR-008 exactly: status_id ->
--                lifecycle_statuses, with NO stored active/is_active boolean
--                (the mission's "active flag" is lifecycle state, not a column).
--                Verification is modeled independently via verification_status_id
--                -> verification_statuses: lifecycle answers "should this barcode
--                participate in the published knowledge base?", verification
--                answers "can this barcode be trusted?".
-- Columns:
--   barcode              Globally unique code value (citext, unique).
--   barcode_type_id      Symbology (FK barcode_types: gtin_13, qr, ...).
--   verification_status_id  Trust status of the code (FK verification_statuses).
--   issued_country_id    GS1 prefix / issuing jurisdiction, NULL = unknown.
--   confidence_level     Fact confidence of this barcode record in [0,1].
-- =============================================================================
CREATE TABLE barcodes (
    id                    uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    barcode               citext        NOT NULL,
    barcode_type_id       uuid          NOT NULL,
    verification_status_id uuid         NOT NULL,
    source_id             uuid          NULL,
    status_id             bigint        NOT NULL,
    issued_country_id     uuid          NULL,
    confidence_level      numeric       NOT NULL DEFAULT 0.5,
    version_number        integer       NOT NULL DEFAULT 1,
    created_by            uuid          NULL,
    updated_by            uuid          NULL,
    reviewed_by           uuid          NULL,
    approved_by           uuid          NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),
    deleted_at            timestamptz   NULL,

    CONSTRAINT barcodes_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT barcodes_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT barcodes_barcode_not_empty_check
        CHECK (barcode <> ''),
    CONSTRAINT barcodes_barcode_unique
        UNIQUE (barcode)
);

COMMENT ON TABLE barcodes IS
    'Canonical registry of globally unique barcodes with lifecycle and verification statuses.';
COMMENT ON COLUMN barcodes.barcode IS
    'Globally unique code value (unique, case-insensitive citext).';
COMMENT ON COLUMN barcodes.barcode_type_id IS
    'Symbology of the code (foreign key to barcode_types: gtin_13, qr, ...).';
COMMENT ON COLUMN barcodes.verification_status_id IS
    'Trust status of the code, orthogonal to lifecycle (foreign key to verification_statuses).';
COMMENT ON COLUMN barcodes.source_id IS
    'Provenance of the barcode record (foreign key to data_sources).';
COMMENT ON COLUMN barcodes.status_id IS
    'Lifecycle of the barcode (foreign key to lifecycle_statuses; ADR-008). No active boolean is stored.';
COMMENT ON COLUMN barcodes.issued_country_id IS
    'Issuing jurisdiction / GS1 prefix country, NULL when unknown (foreign key to countries).';
COMMENT ON COLUMN barcodes.confidence_level IS
    'Fact confidence of this barcode record in [0,1]; the confidence_band ENUM is derived, never stored.';
COMMENT ON COLUMN barcodes.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';
