-- =============================================================================
-- MIGRATION 0029 - media_and_barcode_triggers
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 2 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\07_media_and_barcode_tables_updated_at.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: Media & Barcode Tables updated_at
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared set_updated_at() function to every Mission 07
--                mutable media/barcode table carrying the audit lifecycle
--                columns. Reuses the existing trigger architecture.
-- Work orders:   Mission 07: Canonical Media & Barcode Domain.
-- Dependencies:  Function set_updated_at() (06-functions, 0006). Media/barcode
--                tables (0025).
-- Migration:     0029_media_and_barcode_triggers.sql
-- Rationale:     Every table with updated_at must stamp it on UPDATE. Declaring
--                one trigger per table here keeps the rule explicit and
--                auditable.
-- =============================================================================
CREATE TRIGGER verification_statuses_set_updated_at
    BEFORE UPDATE ON verification_statuses
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER images_set_updated_at
    BEFORE UPDATE ON images
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER barcodes_set_updated_at
    BEFORE UPDATE ON barcodes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\08_media_and_barcode_history_immutability.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: Media & Barcode History Immutability
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared prevent_history_mutation() function to every
--                Mission 07 history table. History rows are INSERT-only: UPDATE
--                and DELETE are rejected at the storage layer.
-- Work orders:   Mission 07: Canonical Media & Barcode Domain.
-- Dependencies:  Function prevent_history_mutation() (06-functions, 0024).
--                Mission 07 history tables (0026).
-- Migration:     0029_media_and_barcode_triggers.sql
-- Rationale:     One trigger per history table keeps the rule explicit and
--                auditable, matching the repository's per-table trigger style.
-- =============================================================================
CREATE TRIGGER images_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON images_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER barcodes_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON barcodes_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();
