-- =============================================================================
-- MIGRATION 0030 - search_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 4 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\65_product_search_index.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_search_index
-- -----------------------------------------------------------------------------
-- Purpose:       Search index for products. A DERIVED READ MODEL, not canonical
--                data: it holds a normalized, denormalized copy of the product's
--                searchable text so that search never scans the canonical
--                registry. Completely disposable and rebuildable from canonical
--                products/product_translations.
-- Work orders:   Mission 08: Search Layer (Derived Read Models).
-- Dependencies:  Extensions pg_trgm / citext (0001). Canonical products and
--                product_translations (0012), product_categories (0008),
--                brands (0012) - referenced LOGICALLY ONLY; there is no foreign
--                key, by design.
-- Migration:     0030_search_tables.sql
-- Rationale:     Canonical entities remain the single source of truth; search
--                owns performance. The product_id column is a logical reference
--                without a FOREIGN KEY constraint so the whole layer can be
--                dropped and rebuilt at any time. UNIQUE (product_id) keeps one
--                row per canonical product, making rebuilds idempotent
--                (truncate + reload, or upsert). No lifecycle, governance, or
--                audit columns: those live on the canonical entity and must not
--                be duplicated (Mission 08 rules). generated_at records when the
--                row was built/refreshed.
-- Deviation:     The standard column layout (audit trio, status_id,
--                version_number) is intentionally NOT followed - this is a
--                derived read model, not a governed entity.
-- Columns:
--   product_id        Logical reference to products.id (NO FK by design).
--   search_name       Normalized primary searchable name (lowercased, folded).
--   search_text       Normalized concatenated searchable text (description,
--                     category, brand, code, aliases - application-built).
--   search_tokens     Language-independent normalized search tokens.
--   language_codes    Languages the searchable text covers (citext codes).
--   search_rank       Ranking helper >= 0 (higher = more prominent).
--   generated_at      When this search row was generated/refreshed.
-- =============================================================================
CREATE TABLE product_search_index (
    id             uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id     uuid        NOT NULL,
    search_name    text        NOT NULL,
    search_text    text        NOT NULL,
    search_tokens  text[]      NOT NULL DEFAULT '{}'::text[],
    language_codes citext[]    NOT NULL DEFAULT '{}'::citext[],
    search_rank    numeric     NOT NULL DEFAULT 0,
    generated_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT product_search_index_product_id_unique
        UNIQUE (product_id),
    CONSTRAINT product_search_index_search_rank_check
        CHECK (search_rank >= 0)
);

COMMENT ON TABLE product_search_index IS
    'Derived, rebuildable search index for products (read model; no FK to products).';
COMMENT ON COLUMN product_search_index.product_id IS
    'Logical reference to products.id; NO foreign key - the search layer is disposable and rebuildable.';
COMMENT ON COLUMN product_search_index.search_name IS
    'Normalized primary searchable name (application-built from canonical name/translations).';
COMMENT ON COLUMN product_search_index.search_text IS
    'Normalized concatenated searchable text: description, category, brand, internal code, aliases.';
COMMENT ON COLUMN product_search_index.search_tokens IS
    'Language-independent normalized search tokens (folded, accent-stripped).';
COMMENT ON COLUMN product_search_index.language_codes IS
    'Languages covered by the searchable text (citext codes, e.g. {ar,en}).';
COMMENT ON COLUMN product_search_index.search_rank IS
    'Ranking helper >= 0; higher means the result is promoted.';
COMMENT ON COLUMN product_search_index.generated_at IS
    'Timestamp when this search row was generated or refreshed (rebuild tracking).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\66_ingredient_search_index.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: ingredient_search_index
-- -----------------------------------------------------------------------------
-- Purpose:       Search index for ingredients. A DERIVED READ MODEL, not
--                canonical data: it holds a normalized, denormalized copy of the
--                ingredient's searchable text so that search never scans the
--                canonical registry. Completely disposable and rebuildable from
--                canonical ingredients/ingredient_translations/aliases.
-- Work orders:   Mission 08: Search Layer (Derived Read Models).
-- Dependencies:  Extensions pg_trgm / citext (0001). Canonical ingredients and
--                ingredient_translations (0012), ingredient_aliases (0016) -
--                referenced LOGICALLY ONLY; there is no foreign key, by design.
-- Migration:     0030_search_tables.sql
-- Rationale:     Canonical entities remain the single source of truth; search
--                owns performance. The ingredient_id column is a logical
--                reference without a FOREIGN KEY constraint so the whole layer
--                can be dropped and rebuilt at any time. UNIQUE (ingredient_id)
--                keeps one row per canonical ingredient, making rebuilds
--                idempotent (truncate + reload, or upsert). No lifecycle,
--                governance, or audit columns: those live on the canonical
--                entity and must not be duplicated (Mission 08 rules).
--                generated_at records when the row was built/refreshed.
-- Deviation:     The standard column layout (audit trio, status_id,
--                version_number) is intentionally NOT followed - this is a
--                derived read model, not a governed entity.
-- Columns:
--   ingredient_id     Logical reference to ingredients.id (NO FK by design).
--   search_name       Normalized primary searchable name (lowercased, folded).
--   search_text       Normalized concatenated searchable text (description,
--                     category, aliases - application-built).
--   search_tokens     Language-independent normalized search tokens.
--   language_codes    Languages the searchable text covers (citext codes).
--   search_rank       Ranking helper >= 0 (higher = more prominent).
--   generated_at      When this search row was generated/refreshed.
-- =============================================================================
CREATE TABLE ingredient_search_index (
    id             uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ingredient_id  uuid        NOT NULL,
    search_name    text        NOT NULL,
    search_text    text        NOT NULL,
    search_tokens  text[]      NOT NULL DEFAULT '{}'::text[],
    language_codes citext[]    NOT NULL DEFAULT '{}'::citext[],
    search_rank    numeric     NOT NULL DEFAULT 0,
    generated_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ingredient_search_index_ingredient_id_unique
        UNIQUE (ingredient_id),
    CONSTRAINT ingredient_search_index_search_rank_check
        CHECK (search_rank >= 0)
);

COMMENT ON TABLE ingredient_search_index IS
    'Derived, rebuildable search index for ingredients (read model; no FK to ingredients).';
COMMENT ON COLUMN ingredient_search_index.ingredient_id IS
    'Logical reference to ingredients.id; NO foreign key - the search layer is disposable and rebuildable.';
COMMENT ON COLUMN ingredient_search_index.search_name IS
    'Normalized primary searchable name (application-built from canonical name/translations).';
COMMENT ON COLUMN ingredient_search_index.search_text IS
    'Normalized concatenated searchable text: description, category, aliases.';
COMMENT ON COLUMN ingredient_search_index.search_tokens IS
    'Language-independent normalized search tokens (folded, accent-stripped).';
COMMENT ON COLUMN ingredient_search_index.language_codes IS
    'Languages covered by the searchable text (citext codes, e.g. {ar,en}).';
COMMENT ON COLUMN ingredient_search_index.search_rank IS
    'Ranking helper >= 0; higher means the result is promoted.';
COMMENT ON COLUMN ingredient_search_index.generated_at IS
    'Timestamp when this search row was generated or refreshed (rebuild tracking).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\67_brand_search_index.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: brand_search_index
-- -----------------------------------------------------------------------------
-- Purpose:       Search index for brands. A DERIVED READ MODEL, not canonical
--                data: it holds a normalized, denormalized copy of the brand's
--                searchable text so that search never scans the canonical
--                registry. Completely disposable and rebuildable from canonical
--                brands/brand_translations.
-- Work orders:   Mission 08: Search Layer (Derived Read Models).
-- Dependencies:  Extensions pg_trgm / citext (0001). Canonical brands and
--                brand_translations (0012), companies (0012) - referenced
--                LOGICALLY ONLY; there is no foreign key, by design.
-- Migration:     0030_search_tables.sql
-- Rationale:     Canonical entities remain the single source of truth; search
--                owns performance. The brand_id column is a logical reference
--                without a FOREIGN KEY constraint so the whole layer can be
--                dropped and rebuilt at any time. UNIQUE (brand_id) keeps one
--                row per canonical brand, making rebuilds idempotent
--                (truncate + reload, or upsert). No lifecycle, governance, or
--                audit columns: those live on the canonical entity and must not
--                be duplicated (Mission 08 rules). generated_at records when the
--                row was built/refreshed.
-- Deviation:     The standard column layout (audit trio, status_id,
--                version_number) is intentionally NOT followed - this is a
--                derived read model, not a governed entity.
-- Columns:
--   brand_id          Logical reference to brands.id (NO FK by design).
--   search_name       Normalized primary searchable name (lowercased, folded).
--   search_text       Normalized concatenated searchable text (description,
--                     owning company, code - application-built).
--   search_tokens     Language-independent normalized search tokens.
--   language_codes    Languages the searchable text covers (citext codes).
--   search_rank       Ranking helper >= 0 (higher = more prominent).
--   generated_at      When this search row was generated/refreshed.
-- =============================================================================
CREATE TABLE brand_search_index (
    id             uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    brand_id       uuid        NOT NULL,
    search_name    text        NOT NULL,
    search_text    text        NOT NULL,
    search_tokens  text[]      NOT NULL DEFAULT '{}'::text[],
    language_codes citext[]    NOT NULL DEFAULT '{}'::citext[],
    search_rank    numeric     NOT NULL DEFAULT 0,
    generated_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT brand_search_index_brand_id_unique
        UNIQUE (brand_id),
    CONSTRAINT brand_search_index_search_rank_check
        CHECK (search_rank >= 0)
);

COMMENT ON TABLE brand_search_index IS
    'Derived, rebuildable search index for brands (read model; no FK to brands).';
COMMENT ON COLUMN brand_search_index.brand_id IS
    'Logical reference to brands.id; NO foreign key - the search layer is disposable and rebuildable.';
COMMENT ON COLUMN brand_search_index.search_name IS
    'Normalized primary searchable name (application-built from canonical name/translations).';
COMMENT ON COLUMN brand_search_index.search_text IS
    'Normalized concatenated searchable text: description, owning company, internal code.';
COMMENT ON COLUMN brand_search_index.search_tokens IS
    'Language-independent normalized search tokens (folded, accent-stripped).';
COMMENT ON COLUMN brand_search_index.language_codes IS
    'Languages covered by the searchable text (citext codes, e.g. {ar,en}).';
COMMENT ON COLUMN brand_search_index.search_rank IS
    'Ranking helper >= 0; higher means the result is promoted.';
COMMENT ON COLUMN brand_search_index.generated_at IS
    'Timestamp when this search row was generated or refreshed (rebuild tracking).';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\68_company_search_index.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: company_search_index
-- -----------------------------------------------------------------------------
-- Purpose:       Search index for companies. A DERIVED READ MODEL, not canonical
--                data: it holds a normalized, denormalized copy of the company's
--                searchable text so that search never scans the canonical
--                registry. Completely disposable and rebuildable from canonical
--                companies/company_translations.
-- Work orders:   Mission 08: Search Layer (Derived Read Models).
-- Dependencies:  Extensions pg_trgm / citext (0001). Canonical companies and
--                company_translations (0012), countries (0003) - referenced
--                LOGICALLY ONLY; there is no foreign key, by design.
-- Migration:     0030_search_tables.sql
-- Rationale:     Canonical entities remain the single source of truth; search
--                owns performance. The company_id column is a logical reference
--                without a FOREIGN KEY constraint so the whole layer can be
--                dropped and rebuilt at any time. UNIQUE (company_id) keeps one
--                row per canonical company, making rebuilds idempotent
--                (truncate + reload, or upsert). No lifecycle, governance, or
--                audit columns: those live on the canonical entity and must not
--                be duplicated (Mission 08 rules). generated_at records when the
--                row was built/refreshed.
-- Deviation:     The standard column layout (audit trio, status_id,
--                version_number) is intentionally NOT followed - this is a
--                derived read model, not a governed entity.
-- Columns:
--   company_id        Logical reference to companies.id (NO FK by design).
--   search_name       Normalized primary searchable name (lowercased, folded).
--   search_text       Normalized concatenated searchable text (description,
--                     country, code - application-built).
--   search_tokens     Language-independent normalized search tokens.
--   language_codes    Languages the searchable text covers (citext codes).
--   search_rank       Ranking helper >= 0 (higher = more prominent).
--   generated_at      When this search row was generated/refreshed.
-- =============================================================================
CREATE TABLE company_search_index (
    id             uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id     uuid        NOT NULL,
    search_name    text        NOT NULL,
    search_text    text        NOT NULL,
    search_tokens  text[]      NOT NULL DEFAULT '{}'::text[],
    language_codes citext[]    NOT NULL DEFAULT '{}'::citext[],
    search_rank    numeric     NOT NULL DEFAULT 0,
    generated_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT company_search_index_company_id_unique
        UNIQUE (company_id),
    CONSTRAINT company_search_index_search_rank_check
        CHECK (search_rank >= 0)
);

COMMENT ON TABLE company_search_index IS
    'Derived, rebuildable search index for companies (read model; no FK to companies).';
COMMENT ON COLUMN company_search_index.company_id IS
    'Logical reference to companies.id; NO foreign key - the search layer is disposable and rebuildable.';
COMMENT ON COLUMN company_search_index.search_name IS
    'Normalized primary searchable name (application-built from canonical name/translations).';
COMMENT ON COLUMN company_search_index.search_text IS
    'Normalized concatenated searchable text: description, country, internal code.';
COMMENT ON COLUMN company_search_index.search_tokens IS
    'Language-independent normalized search tokens (folded, accent-stripped).';
COMMENT ON COLUMN company_search_index.language_codes IS
    'Languages covered by the searchable text (citext codes, e.g. {ar,en}).';
COMMENT ON COLUMN company_search_index.search_rank IS
    'Ranking helper >= 0; higher means the result is promoted.';
COMMENT ON COLUMN company_search_index.generated_at IS
    'Timestamp when this search row was generated or refreshed (rebuild tracking).';
