-- =============================================================================
-- MIGRATION 0031 - search_indexes
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 1 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\04-indexes\10_search_indexes.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Indexes: Search Layer (Derived Read Models)
-- -----------------------------------------------------------------------------
-- Purpose:       Search-only indexes over the Mission 08 derived read models.
--                Uses the search capability already approved in ADR-003
--                (pg_trgm): GIN trigram indexes on the normalized text fields
--                for fuzzy/partial matching (language-independent), GIN array
--                indexes on the search tokens for containment/overlap queries,
--                and a btree on search_rank for ranked result ordering.
-- Work orders:   Mission 08: Search Layer (Derived Read Models).
-- Dependencies:  Extension pg_trgm (0001). Search tables (0030).
-- Migration:     0031_search_indexes.sql
-- Rationale:     These are the ONLY indexes on the search tables: no
--                FK-supporting indexes exist because the tables deliberately
--                carry no foreign keys, and no canonical-query indexes are
--                needed on a read model. The UNIQUE ({entity}_id) constraints
--                create their own btree indexes; they are not duplicated here.
--                Rebuild semantics: dropping these indexes is safe - they are
--                recreated by this migration or regenerated by the search layer.
-- =============================================================================
-- product_search_index
CREATE INDEX product_search_index_search_name_trgm_idx
    ON product_search_index USING gin (search_name gin_trgm_ops);

CREATE INDEX product_search_index_search_text_trgm_idx
    ON product_search_index USING gin (search_text gin_trgm_ops);

CREATE INDEX product_search_index_search_tokens_idx
    ON product_search_index USING gin (search_tokens);

CREATE INDEX product_search_index_search_rank_idx
    ON product_search_index (search_rank DESC);

-- ingredient_search_index
CREATE INDEX ingredient_search_index_search_name_trgm_idx
    ON ingredient_search_index USING gin (search_name gin_trgm_ops);

CREATE INDEX ingredient_search_index_search_text_trgm_idx
    ON ingredient_search_index USING gin (search_text gin_trgm_ops);

CREATE INDEX ingredient_search_index_search_tokens_idx
    ON ingredient_search_index USING gin (search_tokens);

CREATE INDEX ingredient_search_index_search_rank_idx
    ON ingredient_search_index (search_rank DESC);

-- brand_search_index
CREATE INDEX brand_search_index_search_name_trgm_idx
    ON brand_search_index USING gin (search_name gin_trgm_ops);

CREATE INDEX brand_search_index_search_text_trgm_idx
    ON brand_search_index USING gin (search_text gin_trgm_ops);

CREATE INDEX brand_search_index_search_tokens_idx
    ON brand_search_index USING gin (search_tokens);

CREATE INDEX brand_search_index_search_rank_idx
    ON brand_search_index (search_rank DESC);

-- company_search_index
CREATE INDEX company_search_index_search_name_trgm_idx
    ON company_search_index USING gin (search_name gin_trgm_ops);

CREATE INDEX company_search_index_search_text_trgm_idx
    ON company_search_index USING gin (search_text gin_trgm_ops);

CREATE INDEX company_search_index_search_tokens_idx
    ON company_search_index USING gin (search_tokens);

CREATE INDEX company_search_index_search_rank_idx
    ON company_search_index (search_rank DESC);
