-- =============================================================================
-- MIGRATION 0032 - ecr_product_media_tables
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 3 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\69_measurement_bases.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: measurement_bases
-- -----------------------------------------------------------------------------
-- Purpose:       Governed registry of nutrition measurement bases: the reference
--                that the amount_value of a product_nutrition_values fact is
--                expressed against (per 100 g, per serving, per package, ...).
-- Work orders:   ECR-001 Blocker 4 (nutrition measurement bases).
-- Dependencies:  Extension citext (0001). Enum set (0002). Lifecycle table
--                lifecycle_statuses (0003). FK applied in 0034.
-- Migration:     0032_ecr_product_media_tables.sql
-- Rationale:     Following ADR-001/ADR-007 the basis is reference/business
--                knowledge, so it is a governed lookup table, NOT an ENUM: new
--                bases are data inserts, never schema changes (future
--                extensibility). The approved canonical codes are per_100g,
--                per_serving and per_package; their seed rows belong to the
--                Phase 8 governed vocabulary (this repository never invents seed
--                data), while the table structure and the UNIQUE code constraint
--                are provided now so product_nutrition_values can reference the
--                basis. The basis is a new additive dimension on the nutrition
--                fact: the natural key of a fact becomes
--                (product, nutrition_type, relationship_type, measurement_basis),
--                so the same fact may legitimately exist per 100 g AND per
--                serving AND per package.
-- Columns:
--   code           Stable machine reference (snake_case, unique).
--   name           Canonical English name of the basis.
--   display_order  Stable ordering for reference pickers and displays.
-- =============================================================================
CREATE TABLE measurement_bases (
    id             uuid         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    code           citext       NOT NULL,
    name           text         NOT NULL,
    description    text         NULL,
    display_order  integer      NOT NULL DEFAULT 0,
    status_id      bigint       NOT NULL,
    version_number integer      NOT NULL DEFAULT 1,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    deleted_at     timestamptz  NULL,

    CONSTRAINT measurement_bases_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT measurement_bases_code_unique
        UNIQUE (code),
    CONSTRAINT measurement_bases_display_order_check
        CHECK (display_order >= 0)
);

COMMENT ON TABLE measurement_bases IS
    'Governed registry of nutrition measurement bases (per_100g, per_serving, per_package, ...).';
COMMENT ON COLUMN measurement_bases.code IS
    'Stable machine reference (snake_case, unique); seed vocabulary belongs to Phase 8.';
COMMENT ON COLUMN measurement_bases.name IS
    'Canonical English name of the measurement basis.';
COMMENT ON COLUMN measurement_bases.display_order IS
    'Stable ordering for reference pickers; non-negative.';
COMMENT ON COLUMN measurement_bases.status_id IS
    'Lifecycle of the basis (foreign key to lifecycle_statuses; ADR-008).';
COMMENT ON COLUMN measurement_bases.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\70_product_images.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_images
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between a product and one of its canonical images
--                (images). A product may own many images (primary, front, back,
--                nutrition panel, ...), each attached via a relationship type;
--                the image record itself stays canonical and is never duplicated
--                here. Future product-like attachments (e.g. to ingredients or
--                brands) extend this pattern, never the images model.
-- Work orders:   ECR-001 Blocker 1 (product<->image connection).
-- Dependencies:  Tables products (0012), images (0025), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0034 (03-constraints).
-- Migration:     0032_ecr_product_media_tables.sql
-- Rationale:     Follows the Mission 04 relationship architecture exactly: the
--                full relationship column set, provenance per row (source_id,
--                evidence_type_id, confidence_level), lifecycle via status_id
--                (ADR-008), monotonic version counter, effective window, soft
--                delete, and a composite UNIQUE (product, image, relationship
--                type) that prevents duplicate assertions while allowing many
--                images per product. Image kind is governed by image_types on the
--                canonical images table (multiple image types supported without
--                schema change). No cascade anywhere (ADR-006).
-- Columns:
--   product_id          Owning product (FK products).
--   image_id            Connected canonical image (FK images).
--   relationship_type_id  Kind of attachment (FK relationship_types).
-- =============================================================================
CREATE TABLE product_images (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    image_id             uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_images_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_images_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_images_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_images_attachment_unique
        UNIQUE (product_id, image_id, relationship_type_id)
);

COMMENT ON TABLE product_images IS
    'Product-to-image attachment relationship (many images per product).';
COMMENT ON COLUMN product_images.product_id IS
    'Owning product (foreign key to products).';
COMMENT ON COLUMN product_images.image_id IS
    'Connected canonical image (foreign key to images); the image row is never duplicated.';
COMMENT ON COLUMN product_images.relationship_type_id IS
    'Kind of attachment (foreign key to relationship_types: primary_image, gallery, ...).';
COMMENT ON COLUMN product_images.effective_from IS
    'Start of validity for this attachment; NULL = from creation.';
COMMENT ON COLUMN product_images.effective_to IS
    'End of validity for this attachment; NULL = currently effective.';
COMMENT ON COLUMN product_images.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\02-tables\71_product_barcodes.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Table: product_barcodes
-- -----------------------------------------------------------------------------
-- Purpose:       Relationship between a product and one of its canonical
--                barcodes (barcodes). A product may carry many barcodes (GTIN-13
--                and GS1 DataMatrix on the same package, one barcode per pack
--                size, regional variants, ...), each attached via a relationship
--                type; the barcode record itself stays canonical and is never
--                duplicated here. Multiple barcode standards are governed by
--                barcode_types on the canonical barcodes table.
-- Work orders:   ECR-001 Blocker 1 (product<->barcode connection).
-- Dependencies:  Tables products (0012), barcodes (0025), relationship_types,
--                data_sources, evidence_types, lifecycle_statuses (0003/0008).
--                FKs applied in 0034 (03-constraints).
-- Migration:     0032_ecr_product_media_tables.sql
-- Rationale:     Follows the Mission 04 relationship architecture exactly: the
--                full relationship column set, provenance per row, lifecycle via
--                status_id (ADR-008), monotonic version counter, effective
--                window, soft delete, and a composite UNIQUE (product, barcode,
--                relationship type) that prevents duplicate assertions while
--                allowing many barcodes per product. No cascade anywhere
--                (ADR-006).
-- Columns:
--   product_id          Owning product (FK products).
--   barcode_id          Connected canonical barcode (FK barcodes).
--   relationship_type_id  Kind of association (FK relationship_types).
-- =============================================================================
CREATE TABLE product_barcodes (
    id                   uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id           uuid          NOT NULL,
    barcode_id           uuid          NOT NULL,
    relationship_type_id uuid          NOT NULL,
    source_id            uuid          NULL,
    evidence_type_id     uuid          NULL,
    confidence_level     numeric       NOT NULL DEFAULT 0.5,
    effective_from       timestamptz   NULL,
    effective_to         timestamptz   NULL,
    verified_at          timestamptz   NULL,
    approved_at          timestamptz   NULL,
    status_id            bigint        NOT NULL,
    version_number       integer       NOT NULL DEFAULT 1,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    deleted_at           timestamptz   NULL,

    CONSTRAINT product_barcodes_version_number_check
        CHECK (version_number > 0),
    CONSTRAINT product_barcodes_confidence_level_check
        CHECK (confidence_level >= 0 AND confidence_level <= 1),
    CONSTRAINT product_barcodes_effective_period_check
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT product_barcodes_association_unique
        UNIQUE (product_id, barcode_id, relationship_type_id)
);

COMMENT ON TABLE product_barcodes IS
    'Product-to-barcode association relationship (many barcodes per product).';
COMMENT ON COLUMN product_barcodes.product_id IS
    'Owning product (foreign key to products).';
COMMENT ON COLUMN product_barcodes.barcode_id IS
    'Connected canonical barcode (foreign key to barcodes); the barcode row is never duplicated.';
COMMENT ON COLUMN product_barcodes.relationship_type_id IS
    'Kind of association (foreign key to relationship_types: primary_barcode, pack_size_variant, ...).';
COMMENT ON COLUMN product_barcodes.effective_from IS
    'Start of validity for this association; NULL = from creation.';
COMMENT ON COLUMN product_barcodes.effective_to IS
    'End of validity for this association; NULL = currently effective.';
COMMENT ON COLUMN product_barcodes.version_number IS
    'Monotonic governance/version counter; starts at 1, increments on governed change.';
