-- =============================================================================
-- MIGRATION 0036 - ecr_functions
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 2 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\06-functions\03_capture_entity_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Function: capture_entity_history()
-- -----------------------------------------------------------------------------
-- Purpose:       Shared trigger function that AUTOMATICALLY records an immutable
--                snapshot into the {table}_history table whenever a tracked
--                entity row is inserted or materially changed. Application
--                developers never maintain history manually.
-- Work orders:   ECR-001 Blocker 3 (automatic history capture).
-- Dependencies:  Extension pgcrypto (0001, digest()/encode()). Lifecycle
--                lifecycle_statuses (0003/0007) for change-type mapping. A
--                matching {table}_history table per wired trigger (0033).
-- Migration:     0036_ecr_functions.sql
-- Rationale:     One generic function serves every tracked table. It reflects on
--                the trigger's own table via information_schema, copies every
--                entity column that exists (possibly renamed) in the history
--                table, and computes the history header itself:
--                  - id            -> original_entity_id
--                  - created_by    -> changed_by
--                  - approved_by   -> approved_by
--                  - updated_at    -> never captured (immutable rows carry none)
--                  - updated_by/reviewed_by -> never captured (not snapshot state)
--                Guarantees:
--                  - version chain: previous_version_id = latest existing history
--                    row for the entity; version_number adapts to the entity's
--                    counter (auto-increments only when the app does not manage
--                    version_number itself, so manual governance is respected).
--                  - immutability: history rows are INSERT-only; the existing
--                    prevent_history_mutation() triggers still reject UPDATE/
--                    DELETE. No trigger fires on the history INSERT (history
--                    tables carry no INSERT triggers), so there is NO recursion.
--                  - no duplicate snapshots: an UPDATE that changes nothing but
--                    updated_at is detected (jsonb comparison excluding
--                    updated_at) and skipped without a history row or a version
--                    bump.
--                  - tamper evidence: snapshot_hash = SHA-256 of the full
--                    snapshot jsonb; checksum = SHA-256 of
--                    snapshot_hash|id|version|change_type.
--                change_set_id stays NULL (no automatic change-set grouping yet);
--                change_reason stays NULL. version_status keeps its 'draft'
--                default (the existing version-status lifecycle semantics are
--                preserved unchanged).
-- =============================================================================
CREATE OR REPLACE FUNCTION capture_entity_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    hist_table      text;
    prev_id         uuid;
    ct              update_type;
    snapshot        jsonb;
    snap_hash       text;
    row_checksum    text;
    col             record;
    target_col      text;
    ins_cols        text[] := '{}';
    ins_vals        text[] := '{}';
    has_updated_by  boolean := false;
    status_code     citext;
BEGIN
    IF TG_TABLE_SCHEMA IS DISTINCT FROM current_schema() THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    hist_table := TG_TABLE_NAME || '_history';

    SELECT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = TG_TABLE_NAME
          AND column_name = 'updated_by'
    ) INTO has_updated_by;

    -- Classify the change.
    IF TG_OP = 'INSERT' THEN
        ct := 'created';
    ELSIF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
        ct := 'archived';
    ELSIF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        ct := 'modified';
    ELSE
        SELECT code INTO status_code FROM lifecycle_statuses WHERE id = NEW.status_id;
        IF status_code = 'ARCHIVED' THEN
            ct := 'archived';
        ELSIF status_code = 'DEPRECATED' THEN
            ct := 'deprecated';
        ELSE
            ct := 'modified';
        END IF;
    END IF;

    -- Avoid duplicate snapshots: an UPDATE that changed nothing except the
    -- trigger-maintained updated_at stamp must not mint a new version.
    IF TG_OP = 'UPDATE' AND (to_jsonb(NEW) - 'updated_at') = (to_jsonb(OLD) - 'updated_at') THEN
        RETURN NEW;
    END IF;

    -- Preserve the version chain: bump the entity counter only when the
    -- application does not manage version_number itself.
    IF TG_OP = 'UPDATE' AND NEW.version_number = OLD.version_number THEN
        NEW.version_number := OLD.version_number + 1;
    END IF;

    -- Build the snapshot column list from the entity columns that exist
    -- (possibly renamed) in the history table.
    FOR col IN
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = TG_TABLE_NAME
          AND column_name NOT IN ('id', 'updated_at', 'updated_by', 'reviewed_by')
        ORDER BY ordinal_position
    LOOP
        target_col := CASE col.column_name
            WHEN 'created_by' THEN 'changed_by'
            WHEN 'approved_by' THEN 'approved_by'
            ELSE col.column_name
        END;

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = hist_table
              AND column_name = target_col
        ) THEN
            ins_cols := ins_cols || quote_ident(target_col);
            IF col.column_name = 'created_by' THEN
                IF has_updated_by THEN
                    ins_vals := ins_vals || format('COALESCE(NEW.%I, NEW.%I)', 'updated_by', 'created_by');
                ELSE
                    ins_vals := ins_vals || format('NEW.%I', 'created_by');
                END IF;
            ELSE
                ins_vals := ins_vals || format('NEW.%I', col.column_name);
            END IF;
        END IF;
    END LOOP;

    -- previous_version_id = the latest history row for this entity.
    EXECUTE format(
        'SELECT id FROM %I WHERE original_entity_id = %L ORDER BY version_number DESC LIMIT 1',
        hist_table, NEW.id
    ) INTO prev_id;

    snapshot     := to_jsonb(NEW) - 'updated_at';
    snap_hash    := encode(digest(snapshot::text, 'sha256'), 'hex');
    row_checksum := encode(
        digest(snap_hash || '|' || NEW.id::text || '|' || NEW.version_number::text || '|' || ct::text, 'sha256'),
        'hex'
    );

    EXECUTE format(
        'INSERT INTO %I (original_entity_id, version_number, previous_version_id, change_type, snapshot_hash, checksum, %s) VALUES (%L, %L, %L, %L, %L, %L, %s)',
        hist_table,
        array_to_string(ins_cols, ', '),
        NEW.id,
        NEW.version_number,
        prev_id,
        ct,
        snap_hash,
        row_checksum,
        array_to_string(ins_vals, ', ')
    );

    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION capture_entity_history() IS
    'Automatically records an immutable snapshot into {table}_history on INSERT/UPDATE of a tracked entity; preserves the version chain, prevents duplicate snapshots, and never recurses.';

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\06-functions\04_validate_entity_relationship_endpoints.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Function: validate_entity_relationship_endpoints()
-- -----------------------------------------------------------------------------
-- Purpose:       Database-level validation for the polymorphic knowledge-graph
--                edge table entity_relationships. The subject_id/object_id
--                endpoints carry no foreign key (the endpoint type is dynamic),
--                so this trigger function verifies at the storage layer that
--                every referenced entity actually exists in its declared entity
--                table. The database REJECTS relationships that reference
--                non-existing entities.
-- Work orders:   ECR-001 Blocker 2 (entity reference validation).
-- Dependencies:  Core entities companies, brands, products, ingredients,
--                allergens, health_flags (0012). Table entity_relationships
--                (0016). Wired by trigger in 0037.
-- Migration:     0036_ecr_functions.sql
-- Rationale:     The endpoint entity-type column is CHECK-constrained to the six
--                canonical core entities, so the mapping below is a closed,
--                explicit CASE (no dynamic SQL, no injection surface). For each
--                endpoint an existence probe runs against the matching entity
--                table; a missing row raises an exception that aborts the whole
--                statement, so an edge can never point at a UUID that does not
--                exist. This complements (does not replace) the existing CHECK
--                constraints, the UNIQUE edge constraint, and the no-self-loop
--                guard. entity_relationships itself is unchanged (no redesign).
-- =============================================================================
CREATE OR REPLACE FUNCTION validate_entity_relationship_endpoints()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    subject_ok boolean;
    object_ok  boolean;
BEGIN
    subject_ok := CASE NEW.subject_entity_type
        WHEN 'companies'    THEN EXISTS (SELECT 1 FROM companies    WHERE id = NEW.subject_id)
        WHEN 'brands'       THEN EXISTS (SELECT 1 FROM brands       WHERE id = NEW.subject_id)
        WHEN 'products'     THEN EXISTS (SELECT 1 FROM products     WHERE id = NEW.subject_id)
        WHEN 'ingredients'  THEN EXISTS (SELECT 1 FROM ingredients  WHERE id = NEW.subject_id)
        WHEN 'allergens'    THEN EXISTS (SELECT 1 FROM allergens    WHERE id = NEW.subject_id)
        WHEN 'health_flags' THEN EXISTS (SELECT 1 FROM health_flags WHERE id = NEW.subject_id)
        ELSE NULL
    END;

    IF subject_ok IS NULL THEN
        RAISE EXCEPTION 'entity_relationships: unknown subject_entity_type %', NEW.subject_entity_type;
    END IF;
    IF NOT subject_ok THEN
        RAISE EXCEPTION 'entity_relationships: subject entity % does not exist (id %)',
            NEW.subject_entity_type, NEW.subject_id;
    END IF;

    object_ok := CASE NEW.object_entity_type
        WHEN 'companies'    THEN EXISTS (SELECT 1 FROM companies    WHERE id = NEW.object_id)
        WHEN 'brands'       THEN EXISTS (SELECT 1 FROM brands       WHERE id = NEW.object_id)
        WHEN 'products'     THEN EXISTS (SELECT 1 FROM products     WHERE id = NEW.object_id)
        WHEN 'ingredients'  THEN EXISTS (SELECT 1 FROM ingredients  WHERE id = NEW.object_id)
        WHEN 'allergens'    THEN EXISTS (SELECT 1 FROM allergens    WHERE id = NEW.object_id)
        WHEN 'health_flags' THEN EXISTS (SELECT 1 FROM health_flags WHERE id = NEW.object_id)
        ELSE NULL
    END;

    IF object_ok IS NULL THEN
        RAISE EXCEPTION 'entity_relationships: unknown object_entity_type %', NEW.object_entity_type;
    END IF;
    IF NOT object_ok THEN
        RAISE EXCEPTION 'entity_relationships: object entity % does not exist (id %)',
            NEW.object_entity_type, NEW.object_id;
    END IF;

    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION validate_entity_relationship_endpoints() IS
    'Rejects entity_relationships rows whose subject or object endpoint does not exist in its declared entity table (database-level polymorphic reference validation).';
