-- =============================================================================
-- MIGRATION 0037 - ecr_triggers
-- -----------------------------------------------------------------------------
-- Purpose:       Assembles the 4 canonical object file(s) below into a
--                single deployable migration. See the referenced schema files for
--                full per-object documentation.
-- Dependencies:  Prior migrations (lower numbers) must be applied first.
-- Rationale:     Applied atomically by scripts/migrate.ps1 and recorded in the
--                schema_migrations ledger with a content checksum.
-- Generated by:  scripts/build_migrations.ps1 - DO NOT EDIT BY HAND.
-- =============================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\09_ecr_capture_history.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: Automatic History Capture (ECR-001, Blocker 3)
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared capture_entity_history() function to every
--                table that owns an immutable {table}_history table, so history
--                is recorded automatically on INSERT and on material UPDATE.
--                Application developers never maintain history manually.
-- Work orders:   ECR-001 Blocker 3 (automatic history capture).
-- Dependencies:  Function capture_entity_history() (06-functions, 0036).
--                Tracked tables: 9 Mission 05 canonical entities, images and
--                barcodes (0025), product_images and product_barcodes (0032).
-- Migration:     0037_ecr_triggers.sql
-- Rationale:     One trigger per tracked table keeps the rule explicit and
--                auditable, matching the repository's per-table trigger style.
--                BEFORE INSERT OR UPDATE allows the trigger to maintain
--                NEW.version_number for the chain. No recursion: history tables
--                carry no INSERT triggers (their only triggers are the
--                INSERT-only prevent_history_mutation guards).
-- =============================================================================
CREATE TRIGGER companies_capture_history
    BEFORE INSERT OR UPDATE ON companies
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER brands_capture_history
    BEFORE INSERT OR UPDATE ON brands
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER products_capture_history
    BEFORE INSERT OR UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER ingredients_capture_history
    BEFORE INSERT OR UPDATE ON ingredients
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER allergens_capture_history
    BEFORE INSERT OR UPDATE ON allergens
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER health_flags_capture_history
    BEFORE INSERT OR UPDATE ON health_flags
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER nutrition_types_capture_history
    BEFORE INSERT OR UPDATE ON nutrition_types
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER product_categories_capture_history
    BEFORE INSERT OR UPDATE ON product_categories
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER ingredient_categories_capture_history
    BEFORE INSERT OR UPDATE ON ingredient_categories
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER images_capture_history
    BEFORE INSERT OR UPDATE ON images
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER barcodes_capture_history
    BEFORE INSERT OR UPDATE ON barcodes
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER product_images_capture_history
    BEFORE INSERT OR UPDATE ON product_images
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

CREATE TRIGGER product_barcodes_capture_history
    BEFORE INSERT OR UPDATE ON product_barcodes
    FOR EACH ROW
    EXECUTE FUNCTION capture_entity_history();

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\10_entity_relationships_validate_endpoints.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: entity_relationships Endpoint Validation (ECR-001, Blocker 2)
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared validate_entity_relationship_endpoints()
--                function to entity_relationships so every INSERT and UPDATE is
--                checked at the storage layer: the database rejects edges whose
--                subject or object endpoint does not exist.
-- Work orders:   ECR-001 Blocker 2 (entity reference validation).
-- Dependencies:  Function validate_entity_relationship_endpoints()
--                (06-functions, 0036). Table entity_relationships (0016).
-- Migration:     0037_ecr_triggers.sql
-- Rationale:     BEFORE INSERT OR UPDATE validates both polymorphic endpoints
--                before the row is stored. entity_relationships itself is
--                unchanged; the validation layer is purely additive.
-- =============================================================================
CREATE TRIGGER entity_relationships_validate_endpoints
    BEFORE INSERT OR UPDATE ON entity_relationships
    FOR EACH ROW
    EXECUTE FUNCTION validate_entity_relationship_endpoints();

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\11_ecr_new_tables_updated_at.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: ECR-001 New Tables updated_at
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared set_updated_at() function to the tables added
--                by ECR-001 that carry the audit lifecycle columns
--                (measurement_bases, product_images, product_barcodes).
-- Work orders:   ECR-001 (Blocker 1 / Blocker 4 new tables).
-- Dependencies:  Function set_updated_at() (06-functions, 0006). New tables
--                (0032).
-- Migration:     0037_ecr_triggers.sql
-- Rationale:     Every table with updated_at must stamp it on UPDATE. Declaring
--                one trigger per table here keeps the rule explicit and auditable.
-- =============================================================================
CREATE TRIGGER measurement_bases_set_updated_at
    BEFORE UPDATE ON measurement_bases
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER product_images_set_updated_at
    BEFORE UPDATE ON product_images
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER product_barcodes_set_updated_at
    BEFORE UPDATE ON product_barcodes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Source file: schema\07-triggers\12_ecr_history_immutability.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- =============================================================================
-- Triggers: ECR-001 History Table Immutability
-- -----------------------------------------------------------------------------
-- Purpose:       Wire the shared prevent_history_mutation() function to the
--                history tables added by ECR-001 (product_images_history,
--                product_barcodes_history). History rows are INSERT-only: UPDATE
--                and DELETE are rejected at the storage layer.
-- Work orders:   ECR-001 Blocker 3 (automatic history capture).
-- Dependencies:  Function prevent_history_mutation() (06-functions, 0024).
--                History tables (0033).
-- Migration:     0037_ecr_triggers.sql
-- Rationale:     Same rule as every other history table: automatic capture
--                writes rows; nobody may change or remove them afterwards.
-- =============================================================================
CREATE TRIGGER product_images_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON product_images_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();

CREATE TRIGGER product_barcodes_history_prevent_mutation
    BEFORE UPDATE OR DELETE ON product_barcodes_history
    FOR EACH ROW
    EXECUTE FUNCTION prevent_history_mutation();
